/* CAD definition browser/editor: isolated draft, explicit atomic Apply, no live model writes. */
(() => {
 'use strict';const root=globalThis.PieniPlanModules=globalThis.PieniPlanModules||{};
 function create(p){let overlay=null;const L=(ko,en)=>p.language()==='ko'?ko:en,clone=v=>JSON.parse(JSON.stringify(v));
  function close(){overlay?.remove();overlay=null;}
  function button(text,run){const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=run;return b;}
  function open(name){if(p.state.toolset!=='cad')return false;close();const token=p.token(),selected=p.state.objects.find(o=>p.state.selectedObjectIds.has(o.id)&&root.cadBlocks.is(o));name=name||selected?.blockName||p.state.blockDefinitions[0]?.name;
   overlay=document.createElement('div');overlay.className='feature-backdrop';overlay.dataset.cadBlockDialog='';const box=document.createElement('section');box.className='feature-dialog';box.setAttribute('role','dialog');box.setAttribute('aria-modal','true');box.setAttribute('aria-label',L('CAD 블록','CAD blocks'));overlay.append(box);document.body.append(overlay);overlay.onclick=e=>{if(e.target===overlay)close();};overlay.onkeydown=e=>{e.stopPropagation();if(e.key==='Escape'){e.preventDefault();close();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s')e.preventDefault();};
   const heading=document.createElement('h2');heading.textContent=L('CAD 블록 · 공유 정의','CAD blocks · shared definitions');box.append(heading);
   const controls=document.createElement('div');controls.className='feature-actions';controls.append(button(L('선택 객체로 만들기 · BLOCK','Create from selection · BLOCK'),()=>{close();p.run('BLOCK');}),button(L('닫기','Close'),close));box.append(controls);
   if(!p.state.blockDefinitions.length){const msg=document.createElement('p');msg.textContent=L('CAD 도형을 선택하고 블록을 만드세요. Plan 구성품은 기존 라이브러리를 사용합니다.','Select CAD geometry and create a block. Plan components use their existing library.');box.append(msg);return true;}
   const select=document.createElement('select');select.setAttribute('aria-label',L('블록 정의','Block definition'));for(const d of p.state.blockDefinitions){const o=document.createElement('option');o.value=d.name;o.textContent=d.name;select.append(o);}select.value=root.cadBlocks.get(name)?.name||p.state.blockDefinitions[0].name;box.append(select);
   const host=document.createElement('div');box.append(host);
   function edit(){host.replaceChildren();const before=clone(root.cadBlocks.get(select.value)),draft=clone(before),canvas=document.createElement('canvas');canvas.width=640;canvas.height=240;canvas.style.cssText='width:100%;height:240px;background:var(--canvas,#fff);border:1px solid var(--border);';host.append(canvas);
    const info=document.createElement('p');info.textContent=L('정의 좌표는 기준점 (0,0)에 상대적입니다. 적용하면 같은 정의를 사용하는 모든 배치가 바뀝니다. 잠긴 배치가 있으면 변경할 수 없습니다.','Coordinates are relative to base (0,0). Apply updates all instances of this definition. Locked instances prevent changes.');host.append(info);
    const list=document.createElement('div');list.style.cssText='max-height:300px;overflow:auto';host.append(list);
    const error=document.createElement('p');error.setAttribute('role','status');host.append(error);
    function preview(){try{const leaves=draft.objects.flatMap(o=>root.cadBlocks.is(o)?root.cadBlocks.expand(o):[o]),g=root.geometryQuery.create({textLayout:o=>({minx:0,miny:0,maxx:(o.text||'').length*(o.height||100)*.6,maxy:o.height||100})}),bounds=leaves.map(o=>g.bounds(o)).filter(Boolean).filter(b=>b.maxx-b.minx<1e10),c=canvas.getContext('2d');c.clearRect(0,0,640,240);if(!bounds.length)return;const b={minx:Math.min(...bounds.map(v=>v.minx)),maxx:Math.max(...bounds.map(v=>v.maxx)),miny:Math.min(...bounds.map(v=>v.miny)),maxy:Math.max(...bounds.map(v=>v.maxy))},z=Math.min(600/Math.max(1,b.maxx-b.minx),200/Math.max(1,b.maxy-b.miny)),point=q=>({x:320+(q.x-(b.minx+b.maxx)/2)*z,y:120-(q.y-(b.miny+b.maxy)/2)*z});c.strokeStyle='#547baf';c.fillStyle='#547baf';c.lineWidth=1.5;
      for(const o of leaves){const edges=root.cadPolyline?.is(o)?root.cadPolyline.get(o).edges:[o];for(const e of edges){c.beginPath();if(e.a&&e.b){const seg=root.geometryQuery.clipLine(e,b);if(!seg)continue;const a=point(seg.a),v=point(seg.b);c.moveTo(a.x,a.y);c.lineTo(v.x,v.y);}else if(e.center&&e.radius){const q=point(e.center);c.arc(q.x,q.y,e.radius*z,-(e.startAngle||0)*Math.PI/180,-((e.startAngle||0)+(e.sweep??360))*Math.PI/180,(e.sweep??360)>=0);}else if(e.points||e.segments){for(const s of e.segments||e.points.slice(1).map((q,i)=>({a:e.points[i],b:q}))){const a=point(s.a),v=point(s.b);c.moveTo(a.x,a.y);c.lineTo(v.x,v.y);}}c.stroke();if(e.type==='cadText'){const q=point(e.point);c.save();c.translate(q.x,q.y);c.rotate(-(e.rotation||0)*Math.PI/180);c.font=Math.max(8,(e.height||100)*z)+'px system-ui';c.fillText(e.text,0,0);c.restore();}}}error.textContent='';}catch(e){error.textContent=p.error?.(e.message)||e.message;}}
    function field(row,label,value,set,type='number'){const lab=document.createElement('label');lab.className='feature-field';const span=document.createElement('span');span.textContent=label;const input=document.createElement('input');input.type=type;if(type==='number')input.step='any';input.value=value??'';input.oninput=()=>{set(type==='number'?Number(input.value):input.value);preview();};lab.append(span,input);row.append(lab);}
    function rows(){list.replaceChildren();if(draft.objects.length>1000){list.append(L('표시 한도 1,000개: 나머지 도형은 보존됩니다.','Display limit 1,000; remaining geometry is preserved.'));}for(const o of draft.objects.slice(0,1000)){const row=document.createElement('details'),summary=document.createElement('summary');summary.textContent=o.type+' · '+o.id;row.append(summary);row.open=draft.objects.length<4;
      for(const k of ['a','b','center','point','p1','p2','labelPoint','vertex','ray1','ray2'])if(o[k])for(const axis of ['x','y'])field(row,k+'.'+axis,o[k][axis],v=>o[k][axis]=v);
      for(const k of ['radius','height','width','rotation','startAngle','sweep','offset','angle'])if(o[k]!=null)field(row,k,o[k],v=>o[k]=v);
      if(o.readonly||o.type==='cadDxfRecord'){const warning=document.createElement('p');warning.textContent=L('원본 보존 객체 · 읽기 전용','Preserved source record · read-only');row.append(warning);for(const input of row.querySelectorAll('input'))input.disabled=true;list.append(row);continue;}if(o.text!=null)field(row,L('내용','Text'),o.text,v=>o.text=v,'text');
      field(row,L('레이어','Layer'),o.cadLayer||'0',v=>o.cadLayer=v,'text');field(row,L('색상 · BYLAYER/BYBLOCK/#hex','Color · BYLAYER/BYBLOCK/#hex'),o.color||'BYLAYER',v=>o.color=v.trim().toUpperCase(),'text');field(row,L('선종류','Linetype'),o.linetype||'BYLAYER',v=>o.linetype=v,'text');
      for(const v of o.vertices||[])for(const axis of ['x','y'])field(row,v.id+'.'+axis,v[axis],n=>v[axis]=n);for(const [i,v] of(o.points||[]).entries())for(const axis of ['x','y'])field(row,i+'.'+axis,v[axis],n=>v[axis]=n);
      if(o.matrix)for(const k of ['a','b','c','d','tx','ty'])field(row,'matrix.'+k,o.matrix[k],v=>o.matrix[k]=v);
      row.append(button(L('도형 제거','Remove geometry'),()=>{draft.objects=draft.objects.filter(x=>x!==o);rows();preview();}));list.append(row);
    }}rows();preview();const actions=document.createElement('div');actions.className='feature-actions';actions.append(button(L('원 추가','Add circle'),()=>{draft.objects.push({id:p.uid('cadCircle'),type:'cadCircle',center:{x:0,y:0},radius:500,cadLayer:'0'});rows();preview();}),button(L('문자 추가','Add text'),()=>{draft.objects.push({id:p.uid('cadText'),type:'cadText',point:{x:0,y:0},text:L('건축 기호','Architectural symbol'),height:180,alignment:'left',rotation:0,cadLayer:'0'});rows();preview();}),button(L('선 추가','Add line'),()=>{draft.objects.push({id:p.uid('cadLine'),type:'cadLine',a:{x:0,y:0},b:{x:1000,y:0},cadLayer:'0'});rows();preview();}),button(L('삽입 · INSERT','Insert · INSERT'),()=>{close();p.run('INSERT');p.run(before.name);}),button(L('정의 적용','Apply definition'),()=>{try{if(!p.current(token))throw Error('stale-context');for(const o of draft.objects)if(o.type==='cadDimension'&&root.cadAnnotation2)o.segments=root.cadAnnotation2.segments(o);p.commit(before,draft);close();}catch(e){error.textContent=p.error?.(e.message)||e.message;p.status(e.message,'error');}}));if(before.readonly){info.textContent=L('외부 참조 블록 정의 · 읽기 전용','External reference block definition · read-only');for(const input of list.querySelectorAll('input'))input.disabled=true;for(const b of actions.querySelectorAll('button'))if(!b.textContent.includes('INSERT'))b.disabled=true;}host.append(actions);
   }select.onchange=edit;edit();select.focus();return true;
  }return Object.freeze({open,close,get active(){return Boolean(overlay);}});
 }root.cadBlockUI=Object.freeze({create});
})();
