/* Document style manager. Drafts remain local; Apply is one inverse transaction. */
(() => {
 'use strict';const root=globalThis.PieniPlanModules=globalThis.PieniPlanModules||{};
 function create(p){let overlay=null;const L=(ko,en)=>p.language()==='ko'?ko:en,clone=v=>JSON.parse(JSON.stringify(v));function close(){overlay?.remove();overlay=null;}
  const button=(text,run)=>{const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=run;return b;};
  function open(){if(p.state.toolset!=='cad')return false;close();const token=p.token();overlay=document.createElement('div');overlay.className='feature-backdrop';const box=document.createElement('section');box.className='feature-dialog';box.setAttribute('role','dialog');box.setAttribute('aria-modal','true');box.setAttribute('aria-label',L('치수 스타일','Dimension styles'));overlay.append(box);document.body.append(overlay);overlay.onclick=e=>{if(e.target===overlay)close();};overlay.onkeydown=e=>{e.stopPropagation();if(e.key==='Escape'){e.preventDefault();close();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s')e.preventDefault();};const title=document.createElement('h2');title.textContent=L('치수 스타일 · DIMSTYLE','Dimension styles · DIMSTYLE');box.append(title);
   const selector=document.createElement('select');selector.setAttribute('aria-label',L('스타일','Style'));const fresh=document.createElement('option');fresh.value='__new__';fresh.textContent=L('새 스타일','New style');selector.append(fresh);for(const d of p.state.dimensionStyles){const o=document.createElement('option');o.value=d.name;o.textContent=d.name;selector.append(o);}selector.value=p.state.toolSettings.dimensionStyleName||p.state.dimensionStyles[0]?.name||'__new__';box.append(selector);
   const host=document.createElement('div');box.append(host);function edit(){host.replaceChildren();const before=selector.value==='__new__'?null:clone(root.cadDimensionStyles.get(selector.value)),draft={...root.cadDimensionStyles.defaults('Architectural 100'),...(before||{})},fields=[],error=document.createElement('p');error.setAttribute('role','status');const note=document.createElement('p');note.textContent=L('크기는 종이 mm, 축척은 모델 표시 배율입니다. 기존 치수의 객체별 재정의는 스타일 적용으로 제거할 수 있습니다.','Sizes are paper millimetres; scale is the model display multiplier. Apply can remove per-object overrides from existing dimensions.');host.append(note);
    function field(key,label,type='number',options=null){const lab=document.createElement('label');lab.className='feature-field';const span=document.createElement('span');span.textContent=label;let input;if(options){input=document.createElement('select');for(const [v,text]of options){const o=document.createElement('option');o.value=v;o.textContent=text;input.append(o);}}else{input=document.createElement('input');input.type=type;if(type==='number')input.step=key==='precision'?'1':'any';}input.value=draft[key]??'';input.disabled=key==='name'&&Boolean(before);lab.append(span,input);host.append(lab);fields.push({key,input,type:options?'select':type});}
    field('name',L('이름','Name'),'text');for(const [key,ko,en]of [['textHeight','문자 크기 · mm','Text size · mm'],['arrowSize','화살표/눈금 크기 · mm','Arrow/tick size · mm'],['extensionOffset','보조선 시작 간격 · mm','Extension offset · mm'],['extensionBeyond','보조선 연장 · mm','Extension beyond · mm'],['textGap','문자 간격 · mm','Text gap · mm'],['overallScale','모델 표시 축척','Model display scale'],['precision','소수점 자릿수','Decimal precision'],['lengthFactor','측정값 배율','Measurement multiplier']])field(key,L(ko,en));
    field('units',L('단위','Units'),'text',[['mm','mm'],['cm','cm'],['m','m'],['in','in'],['ft','ft'],['ft-in',L('피트/인치 · 소수','Feet/inches · decimal')]]);field('arrow',L('끝점 표시','End marker'),'text',[['tick',L('건축 눈금','Architectural tick')],['closed',L('채운 화살표','Closed arrow')],['open',L('열린 화살표','Open arrow')],['none',L('없음','None')]]);field('textPosition',L('문자 위치','Text position'),'text',[['above',L('치수선 위','Above line')],['center',L('치수선 가운데','On line')]]);field('textOrientation',L('문자 방향','Text orientation'),'text',[['aligned',L('치수선 방향','Along dimension')],['horizontal',L('수평','Horizontal')]]);field('format',L('표시 형식 · <>는 측정값','Format · <> is the measurement'),'text');const showUnit=document.createElement('input');showUnit.type='checkbox';showUnit.checked=draft.showUnit!==false;const unitLabel=document.createElement('label');unitLabel.append(showUnit,document.createTextNode(L('단위 표시','Show units')));host.append(unitLabel,error);
    const read=()=>{for(const {key,input,type}of fields)draft[key]=type==='number'?Number(input.value):input.value;draft.name=draft.name.trim();draft.showUnit=showUnit.checked;if(before&&before.arrow!==draft.arrow){delete draft.arrowBlock;delete draft.arrowBlock1;delete draft.arrowBlock2;}root.cadDimensionStyles.validate([draft]);return draft;},apply=selection=>{try{if(!p.current(token))throw Error('stale-context');const d=read();p.commit(before,d,{apply:selection,current:true});close();}catch(e){error.textContent=p.error?.(e.message)||e.message;}};
    const actions=document.createElement('div');actions.className='feature-actions';actions.append(button(L('취소','Cancel'),close),button(L('저장하고 현재 스타일로','Save as current style'),()=>apply(false)),button(L('선택 치수에 적용 · 재정의 제거','Apply to selected dimensions · clear overrides'),()=>apply(true)));if(before)actions.append(button(L('스타일 삭제','Delete style'),()=>{try{p.remove(before);close();}catch(e){error.textContent=p.error?.(e.message)||e.message;}}));host.append(actions);
   }selector.onchange=edit;edit();selector.focus();return true;
  }return Object.freeze({open,close,get active(){return Boolean(overlay);}});
 }root.dimensionStyleUI=Object.freeze({create});
})();
