/* Reuses the existing Sheet/PDF model. Metadata edits are explicit and undoable. */
(() => {
 'use strict';const root=globalThis.PieniPlanModules=globalThis.PieniPlanModules||{};
 function create(p){let overlay=null;const L=(k,e)=>p.language()==='ko'?k:e,clone=v=>JSON.parse(JSON.stringify(v)),button=(text,fn)=>{const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=fn;return b;};function close(){overlay?.remove();overlay=null;}
  function open(){close();overlay=document.createElement('div');overlay.className='feature-backdrop';const box=document.createElement('section');box.className='feature-dialog';box.setAttribute('role','dialog');box.setAttribute('aria-modal','true');box.setAttribute('aria-label',L('시트 관리','Sheets'));overlay.append(box);document.body.append(overlay);overlay.onkeydown=e=>{e.stopPropagation();if(e.key==='Escape'){e.preventDefault();close();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s')e.preventDefault();};overlay.onclick=e=>{if(e.target===overlay)close();};const h=document.createElement('h2');h.textContent=L('시트 관리','Sheets');box.append(h);const select=document.createElement('select');select.setAttribute('aria-label',L('시트','Sheet'));for(const s of p.state.sheets){const o=document.createElement('option');o.value=s.id;o.textContent=s.name;select.append(o);}box.append(select);const host=document.createElement('div');box.append(host);
   function edit(){host.replaceChildren();const original=p.state.sheets.find(s=>s.id===select.value);if(!original){const n=document.createElement('p');n.textContent=L('출력에서 시트를 저장하거나 새 시트를 만드세요.','Save a sheet through output, or create a new sheet.');host.append(n);return;}const before=clone(original),draft=clone(original),fields=[],error=document.createElement('p');error.setAttribute('role','status');
    function field(key,label,type='text',options=null){const lab=document.createElement('label');lab.className='feature-field';const span=document.createElement('span');span.textContent=label;let input;if(options){input=document.createElement('select');for(const [v,t]of options){const o=document.createElement('option');o.value=v;o.textContent=t;input.append(o);}}else{input=document.createElement('input');input.type=type;if(type==='number')input.step='any';}input.value=draft[key]??'';lab.append(span,input);host.append(lab);fields.push({key,input,type});}
    for(const [k,ko,en]of [['name','시트 이름','Sheet name'],['drawingName','도면명','Drawing name'],['drawingNumber','도면번호','Drawing number'],['revision','개정','Revision'],['date','작성일','Date']])field(k,L(ko,en));field('paper',L('용지','Paper'),'text',Object.keys(root.sheetLayout.papers).map(v=>[v,v]));field('orientation',L('방향','Orientation'),'text',[['landscape',L('가로','Landscape')],['portrait',L('세로','Portrait')]]);field('scale',L('출력 축척 · 1:','Plot scale · 1:'),'number');const note=document.createElement('p');note.textContent=L('저장된 모델 범위와 층 연결을 유지합니다. 출력에서 범위를 조정하고 PDF를 만들 수 있습니다.','The saved model range and floor association are retained. Adjust the range and generate PDF through output.');host.append(note,error);const actions=document.createElement('div');actions.className='feature-actions';actions.append(button(L('메타데이터 저장','Save metadata'),()=>{try{for(const {key,input,type}of fields)draft[key]=type==='number'?Number(input.value):input.value;draft.sizeMode='fixed';p.commit(before,draft);open();}catch(e){error.textContent=e.message;}}),button(L('복제','Duplicate'),()=>{try{const copy={...draft,id:p.uid('sheet'),name:draft.name+' · '+L('복사','Copy')};p.commit(null,copy);open();}catch(e){error.textContent=e.message;}}),button(L('삭제','Delete'),()=>{p.commit(before,null);open();}),button(L('PDF 출력','PDF output'),()=>{close();p.output({...draft,project:p.state.projectId,rangeMode:'direct',tempRange:draft.range,content:draft.content||p.defaults()});}));host.append(actions);
   }select.onchange=edit;edit();const controls=document.createElement('div');controls.className='feature-actions';controls.append(button(L('새 시트 · 현재 화면','New sheet · current view'),()=>{const page=p.view(),sheet={id:p.uid('sheet'),name:'Sheet '+(p.state.sheets.length+1),mode:p.state.toolset,floorId:page.floorId,regionId:page.regionId,rotation:page.rotation||0,range:page.range,paper:'A3',orientation:'landscape',sizeMode:'fit',scale:100,margins:{top:10,right:10,bottom:10,left:10},content:p.defaults()};p.commit(null,sheet);open();}),button(L('닫기','Close'),close));box.append(controls);select.focus();return true;
  }return Object.freeze({open,close,get active(){return Boolean(overlay);}});
 }root.sheetUI=Object.freeze({create});
})();
