/* One semantic stair owns its footprint. Treads and arrow are derived vectors, never walls. */
(() => {
 'use strict';const root=globalThis.PieniPlanModules=globalThis.PieniPlanModules||{};
 const add=(a,b)=>({x:a.x+b.x,y:a.y+b.y}),mul=(a,n)=>({x:a.x*n,y:a.y*n});
 function frame(o){const p=o?.polygon;if(!p||p.length!==4)return null;const w={x:p[1].x-p[0].x,y:p[1].y-p[0].y},l={x:p[3].x-p[0].x,y:p[3].y-p[0].y},width=Math.hypot(w.x,w.y),length=Math.hypot(l.x,l.y);if(width<1e-6||length<1e-6)return null;return{origin:p[0],u:mul(w,1/width),v:mul(l,1/length),width,length,rotation:Math.atan2(w.y,w.x)*180/Math.PI};}
 function footprint(origin,width,length,rotation=0){if(![origin.x,origin.y,width,length,rotation].every(Number.isFinite)||width<=0||length<=0)throw new Error('invalid-stair-size');const a=rotation*Math.PI/180,u={x:Math.cos(a),y:Math.sin(a)},v={x:-u.y,y:u.x};return[origin,add(origin,mul(u,width)),add(add(origin,mul(u,width)),mul(v,length)),add(origin,mul(v,length))].map(p=>({...p}));}
 function edit(o,patch){const f=frame(o);if(!f)throw new Error('unsupported-stair-footprint');const width=patch.width??f.width,length=patch.length??f.length,count=patch.treadCount??o.treadCount??12;if(!Number.isInteger(count)||count<2||count>256||![1,-1].includes(patch.upDirection??o.upDirection??1))throw new Error('invalid-stair-properties');return{...o,polygon:footprint(f.origin,width,length,patch.rotation??f.rotation),treadCount:count,upDirection:patch.upDirection??o.upDirection??1};}
 function segments(o){const f=frame(o);if(!f)return(o?.polygon||[]).map((a,i,p)=>({a,b:p[(i+1)%p.length]}));const result=o.polygon.map((a,i,p)=>({a,b:p[(i+1)%p.length]})),n=Math.max(2,Math.min(256,Number(o.treadCount)||12));const pt=(x,y)=>add(add(f.origin,mul(f.u,x)),mul(f.v,y));for(let i=1;i<n;i++)result.push({a:pt(0,f.length*i/n),b:pt(f.width,f.length*i/n)});const reverse=o.upDirection===-1,from=pt(f.width/2,f.length*(reverse?.82:.18)),to=pt(f.width/2,f.length*(reverse?.18:.82)),head=Math.min(f.width*.16,f.length*.08),direction=reverse?-1:1;result.push({a:from,b:to},{a:to,b:add(add(to,mul(f.v,-head*direction)),mul(f.u,head*.6))},{a:to,b:add(add(to,mul(f.v,-head*direction)),mul(f.u,-head*.6))});return result;}
 root.planStair=Object.freeze({frame,footprint,edit,segments});
})();
