/* CAD definition/instance algebra. Persistent definitions belong to the document.
 * Expansion is derived, bounded and cached; no definition is copied into an instance. */
(() => {
 'use strict';const root=globalThis.PieniPlanModules=globalThis.PieniPlanModules||{};
 const is=o=>o?.type==='cadInsert',clone=o=>JSON.parse(JSON.stringify(o)),finite=Number.isFinite;
 const identity=()=>({a:1,b:0,c:0,d:1,tx:0,ty:0}),point=(m,p)=>({x:m.a*p.x+m.c*p.y+m.tx,y:m.b*p.x+m.d*p.y+m.ty});
 const mul=(a,b)=>({a:a.a*b.a+a.c*b.b,b:a.b*b.a+a.d*b.b,c:a.a*b.c+a.c*b.d,d:a.b*b.c+a.d*b.d,tx:a.a*b.tx+a.c*b.ty+a.tx,ty:a.b*b.tx+a.d*b.ty+a.ty});
 const matrixValid=m=>m&&[m.a,m.b,m.c,m.d,m.tx,m.ty].every(finite)&&finite(m.a*m.d-m.b*m.c)&&Math.abs(m.a*m.d-m.b*m.c)>1e-12;
 const matrix=(p={x:0,y:0},rotation=0,sx=1,sy=sx)=>{const a=rotation*Math.PI/180,c=Math.cos(a),s=Math.sin(a);return{a:c*sx,b:s*sx,c:-s*sy,d:c*sy,tx:p.x,ty:p.y};};
 const inverse=m=>{const det=m.a*m.d-m.b*m.c;if(Math.abs(det)<1e-12)throw Error('singular-block-transform');return{a:m.d/det,b:-m.b/det,c:-m.c/det,d:m.a/det,tx:(m.c*m.ty-m.d*m.tx)/det,ty:(m.b*m.tx-m.a*m.ty)/det};};
 const similarity=m=>{const x=Math.hypot(m.a,m.b),y=Math.hypot(m.c,m.d);return Math.abs(x-y)<1e-8*Math.max(x,y)&&Math.abs(m.a*m.c+m.b*m.d)<1e-8*x*y;};
 let defs=()=>[],layers=()=>null,source=null,layerSource=null,cache=new WeakMap(),localBounds=new WeakMap(),retained=new Map(),retainedCost=0,byName=new Map();
 function configure(getDefs,getLayer,getLayerSource=()=>null){defs=getDefs;layers=getLayer;layerSource=getLayerSource;source=null;cache=new WeakMap();localBounds=new WeakMap();retained=new Map();retainedCost=0;}
 function store(){const next=defs()||[];if(source!==next){source=next;byName=new Map(next.map(d=>[d.name.toUpperCase(),d]));cache=new WeakMap();localBounds=new WeakMap();retained=new Map();retainedCost=0;}return byName;}
 function validate(definitions,objects=[]){if(!Array.isArray(definitions)||definitions.length>10000)throw Error('invalid-block-definitions');const map=new Map();
  for(const d of definitions){if(!d||typeof d.name!=='string'||!d.name.trim()||/[\x00-\x1f]/.test(d.name)||/[<>/\\":;?*=]/.test(d.name.replace(/^\*/,''))||(!d.dxfHeader&&/\|/.test(d.name))||map.has(d.name.toUpperCase())||!Array.isArray(d.objects)||d.objects.length>100000)throw Error('invalid-block-definition');map.set(d.name.toUpperCase(),d);const ids=new Set();for(const o of d.objects){if(!o.id||ids.has(o.id)||o.floorId||o.planRole)throw Error('invalid-block-member');ids.add(o.id);}}
  const visiting=new Set(),done=new Set(),cost=new Map(),height=new Map();function visit(name,depth=0){name=String(name).toUpperCase();if(depth>32||visiting.has(name))throw Error('cyclic-or-deep-block');if(done.has(name)){if(depth+height.get(name)>32)throw Error('cyclic-or-deep-block');return cost.get(name);}const d=map.get(name);if(!d)throw Error('missing-block-definition:'+name);visiting.add(name);let total=0,h=0;for(const o of d.objects){if(is(o)){if(!matrixValid(o.matrix))throw Error('invalid-block-transform');total+=visit(o.blockName,depth+1);h=Math.max(h,1+height.get(String(o.blockName).toUpperCase()));}else total+=memberCost(o);if(total>100000)throw Error('block-expansion-budget');}visiting.delete(name);done.add(name);cost.set(name,total);height.set(name,h);return total;}
  for(const name of map.keys())visit(name);for(const o of objects)if(is(o)){if(!matrixValid(o.matrix))throw Error('invalid-block-transform');visit(o.blockName);}return definitions;
 }
 const memberCost=o=>Math.max(1,o.vertices?.length||o.points?.length||o.preview?.reduce((n,q)=>n+memberCost(q),0)||1);
 function bounds(instance,leafBounds){store();const styleSource=layerSource();let cacheFor=localBounds.get(leafBounds);if(!cacheFor||cacheFor.styleSource!==styleSource){cacheFor={styleSource,map:new Map()};localBounds.set(leafBounds,cacheFor);}const merge=(a,b)=>!a?b:!b?a:{minx:Math.min(a.minx,b.minx),maxx:Math.max(a.maxx,b.maxx),miny:Math.min(a.miny,b.miny),maxy:Math.max(a.maxy,b.maxy)},transform=(b,m)=>{if(!b)return null;const pts=[{x:b.minx,y:b.miny},{x:b.maxx,y:b.miny},{x:b.maxx,y:b.maxy},{x:b.minx,y:b.maxy}].map(p=>point(m,p));return{minx:Math.min(...pts.map(p=>p.x)),maxx:Math.max(...pts.map(p=>p.x)),miny:Math.min(...pts.map(p=>p.y)),maxy:Math.max(...pts.map(p=>p.y))};};
  function local(name,path=[]){const key=name.toUpperCase();if(path.includes(key)||path.length>=32)throw Error('cyclic-or-deep-block');if(cacheFor.map.has(key))return cacheFor.map.get(key);const d=store().get(key);if(!d)throw Error('missing-block-definition:'+name);let b=null;for(const o of d.objects)b=merge(b,is(o)?transform(local(o.blockName,[...path,key]),o.matrix):leafBounds(o));cacheFor.map.set(key,b);return b;}return transform(local(instance.blockName),instance.matrix);
 }
 function previewBudget(instance){let total=0;function walk(name,m,depth=0){if(!matrixValid(m))throw Error('invalid-block-transform');if(depth>32)throw Error('cyclic-or-deep-block');const d=store().get(name.toUpperCase());if(!d)throw Error('missing-block-definition');for(const o of d.objects){if(is(o))walk(o.blockName,mul(m,o.matrix),depth+1);else if(o.type==='cadDimension'&&root.cadDimensionStyles){const picture=root.cadDimensionStyles.presentation(o),scene=picture?[picture]:root.cadDimensionStyles.scene(o,{force:true});for(const q of scene||[]){if(is(q))walk(q.blockName,mul(m,q.matrix),depth+1);else total+=memberCost(q);}}else if(!similarity(m)&&root.cadPolyline?.is(o)){for(const v of o.vertices)total+=v.outgoing?.bulge?Math.max(4,Math.ceil(Math.abs(4*Math.atan(v.outgoing.bulge))*180/Math.PI/3)):1;}else total+=!similarity(m)&&(o.type==='cadCircle'||o.type==='cadArc')?120:memberCost(o);if(total>100000)throw Error('block-preview-geometry-budget');}}walk(instance.blockName,instance.matrix);return total;}
 function appearance(o,parent={}){const name=(o.cadLayer||'0')==='0'?(parent.cadLayer||'0'):o.cadLayer,l=layers(name)||{},pick=(key,fallback)=>o[key]==='BYBLOCK'||o[key]===-2?parent[key]??fallback:o[key]==null||o[key]==='BYLAYER'||o[key]===-1?l[key]??fallback:o[key],byBlock=o.color==='BYBLOCK'||o.color===-2,byLayer=o.color==null||o.color==='BYLAYER'||o.color===-1,color=pick('color',null),adaptiveColor=byBlock?Boolean(parent.adaptiveColor):byLayer?l.colorIndex===7&&l.color==='#111111':o.colorIndex===7&&o.color==='#111111';return{cadLayer:name,color,adaptiveColor,linetype:pick('linetype','CONTINUOUS'),lineweight:pick('lineweight','DEFAULT')};}
 function transformLeaf(o,m,{approximate=false}={}){if(is(o))return{...o,matrix:mul(m,o.matrix)};
  if(o.type==='cadText'&&(m.a*m.d-m.b*m.c<0||!similarity(m))){if(!approximate)throw Error('explode-nonuniform-geometry-not-supported');const h=Math.hypot(m.c,m.d),r=Math.atan2(m.b,m.a)*180/Math.PI;return{...o,point:point(m,o.point),height:o.height*h,width:(o.width||0)*Math.hypot(m.a,m.b),rotation:(o.rotation||0)+r,affine:{matrix:m,original:o},approximation:'affine-text'};}
  if(similarity(m)){const result=root.cadTransformOperations.transform(o,m);if(result)return result;}
  if(o.type==='cadPoint')return{...o,point:point(m,o.point)};
  if(o.type==='cadLine'||o.type==='cadRay'||o.type==='cadXline')return{...o,a:point(m,o.a),b:point(m,o.b)};
  if(root.cadPolyline?.is(o)&&o.vertices.every(v=>!v.outgoing?.bulge))return{...o,vertices:o.vertices.map(v=>({...v,...point(m,v)}))};
  if(root.cadPolyline?.is(o)&&approximate){const points=[];for(const e of root.cadPolyline.get(o).edges){if(!points.length)points.push(point(m,e.type==='cadLine'?e.a:root.geometryQuery.pointAt(e,e.startAngle)));if(e.type==='cadLine')points.push(point(m,e.b));else{const n=Math.max(4,Math.ceil(Math.abs(e.sweep)/3));for(let i=1;i<=n;i++)points.push(point(m,root.geometryQuery.pointAt(e,e.startAngle+e.sweep*i/n)));if(points.length>100000)throw Error('block-preview-geometry-budget');}}if(o.closed&&points.length>1)points.pop();return{...o,vertices:points.map((p,i)=>({id:o.id+'-av'+i,...p,...(i<points.length-1||o.closed?{outgoing:{id:o.id+'-ae'+i,bulge:0}}:{})})),approximation:'nonuniform-polyline'};}
  if(o.type==='cadHatch'){const q={...o,points:o.points.map(p=>point(m,p)),loops:o.loops?.map(loop=>loop.map(p=>point(m,p)))};if(o.dxf?.raw||o.hatchPatternTransform)q.hatchPatternTransform=mul(m,o.hatchPatternTransform||identity());return q;}
  if(o.type==='cadDxfRecord')return{...o,preview:(o.preview||[]).map(q=>transformLeaf(q,m,{approximate:true})),readonly:true};
  if(!approximate)throw Error('explode-nonuniform-geometry-not-supported');
  if(o.type==='cadCircle'||o.type==='cadArc'){const start=o.startAngle||0,sweep=o.type==='cadCircle'?360:o.sweep,n=Math.max(32,Math.ceil(Math.abs(sweep)/3)),points=Array.from({length:n+1},(_,i)=>point(m,{x:o.center.x+o.radius*Math.cos((start+sweep*i/n)*Math.PI/180),y:o.center.y+o.radius*Math.sin((start+sweep*i/n)*Math.PI/180)}));return{...o,type:'cadLeader',points,center:point(m,o.center),height:1,text:'',blockSnapPoints:[{...point(m,o.center),kind:'center'},...[0,.5,1].map(t=>({...point(m,{x:o.center.x+o.radius*Math.cos((start+sweep*t)*Math.PI/180),y:o.center.y+o.radius*Math.sin((start+sweep*t)*Math.PI/180)}),kind:t===.5?'midpoint':'endpoint'}))],approximation:'nonuniform-curve'};}
  if(o.type==='cadText'){const h=Math.hypot(m.c,m.d),r=Math.atan2(m.b,m.a)*180/Math.PI;return{...o,point:point(m,o.point),height:o.height*h,width:(o.width||0)*Math.hypot(m.a,m.b),rotation:(o.rotation||0)+r,affine:{matrix:m,original:o},approximation:'nonuniform-text'};}
  throw Error('unsupported-block-geometry:'+o.type);
 }
 function expand(instance,{approximate=true}={}){store();const styleSource=layerSource();const sig=JSON.stringify([instance.matrix,instance.cadLayer,instance.color,instance.linetype,instance.lineweight,approximate]);const dimSource=root.cadDimensionStyles?.library?.(),known=cache.get(instance);if(known&&known.source===source&&known.styleSource===styleSource&&known.dimSource===dimSource&&known.sig===sig)return known.items;
  const out=[],seen=[];function walk(o,m,parent,path){if(out.length>100000)throw Error('block-expansion-budget');const props=appearance(o,parent);if(is(o)){const d=store().get(String(o.blockName).toUpperCase());if(!d)throw Error('missing-block-definition:'+o.blockName);if(seen.includes(o.blockName)||seen.length>=32)throw Error('cyclic-or-deep-block');seen.push(o.blockName);const combined=mul(m,o.matrix);for(const child of d.objects)walk(child,combined,props,path+'/'+child.id);seen.pop();}else if(o.type==='cadDimension'&&root.cadDimensionStyles){const picture=root.cadDimensionStyles.presentation(o),scene=picture?[picture]:root.cadDimensionStyles.scene(o,{force:true});for(const child of scene||[])walk(child,m,props,path+'/'+child.id);}else{const q={...transformLeaf(o,m,{approximate}),...props,id:path,blockOwnerId:instance.blockOwnerId||instance.id};if(root.cadPolyline?.is(q))q.vertices=q.vertices.map(v=>({...v,id:path+'/'+v.id,...(v.outgoing?{outgoing:{...v.outgoing,id:path+'/'+v.outgoing.id}}:{})}));out.push(q);}}
  walk(instance,identity(),{},instance.id);const cost=out.reduce((n,q)=>n+memberCost(q),0);if(retained.has(instance)){retainedCost-=retained.get(instance);retained.delete(instance);}if(cost<=200000){cache.set(instance,{source,styleSource,dimSource,sig,items:out});retained.set(instance,cost);retainedCost+=cost;while(retainedCost>200000){const [owner,cost]=retained.entries().next().value;retained.delete(owner);cache.delete(owner);retainedCost-=cost;}}return out;
 }
 function definition(name,objects,base){if(String(name).startsWith('*'))throw Error('reserved-block-name');if(!base||!finite(base.x)||!finite(base.y))throw Error('invalid-block-base');const m=matrix({x:-base.x,y:-base.y});return{name,base:{x:0,y:0},objects:objects.map(o=>{if(o.floorId||o.planRole)throw Error('plan-object-cannot-be-blocked');const q=transformLeaf(clone(o),m);delete q.selected;return q;})};}
 function explode(instance,uid){const seen=new Set();function check(name){const d=store().get(String(name).toUpperCase()),k=d?.name.toUpperCase();if(!d)throw Error('missing-block-definition');if(seen.has(k))return;seen.add(k);if(d.readonly||d.objects.some(o=>o.readonly||o.type==='cadDxfRecord'))throw Error('block-content-readonly');for(const o of d.objects)if(is(o))check(o.blockName);}check(instance.blockName);const objects=expand(instance,{approximate:false});return objects.map(o=>{const q=clone(o);q.id=uid(q.type);delete q.blockOwnerId;if(root.cadPolyline?.is(q))q.vertices=q.vertices.map(v=>({...v,id:uid('cadVertex'),...(v.outgoing?{outgoing:{...v.outgoing,id:uid('cadEdge')}}:{})}));return q;});}
 root.cadBlocks=Object.freeze({capability:'cad.block.v1',is,configure,validate,expand,bounds,memberCost,previewBudget,appearance,definition,explode,matrix,matrixValid,inverse,multiply:mul,point,similarity,transformLeaf,get:name=>store().get(String(name).toUpperCase())||null});
})();
