/* Dimension styles are document libraries. Unstyled legacy dimensions retain legacy display. */
(() => {
 'use strict';const root=globalThis.PieniPlanModules=globalThis.PieniPlanModules||{},units={mm:1,cm:10,m:1000,in:25.4,ft:304.8,'ft-in':1};let definitions=()=>[],blocks=()=>[],blockSource=null,blockMap=new Map();
 const defaults=name=>({name,textHeight:2.5,arrowSize:2.5,extensionOffset:.625,extensionBeyond:1.25,textGap:.625,overallScale:100,precision:0,units:'mm',lengthFactor:1,arrow:'tick',textOrientation:'aligned',format:'<>',showUnit:true,textPosition:'above'});
 function configure(styles,blockLibrary=()=>[]){definitions=styles;blocks=blockLibrary;}
 function validate(styles){if(!Array.isArray(styles)||styles.length>10000)throw Error('invalid-dimension-style-library');const names=new Set();for(const d of styles){const k=String(d?.name||'').toUpperCase();if(!k||/[\x00-\x1f<>/\\":;?*=]/.test(k)||(!d.dxf&&/\|/.test(k))||names.has(k))throw Error('invalid-dimension-style-name');names.add(k);for(const key of ['textHeight','overallScale','lengthFactor'])if(!Number.isFinite(d[key])||d[key]<=0)throw Error('invalid-dimension-style-'+key);if(!Number.isFinite(d.arrowSize)||d.arrowSize<0)throw Error('invalid-dimension-arrow-size');for(const key of ['extensionOffset','extensionBeyond','textGap'])if(d[key]!=null&&(!Number.isFinite(d[key])||d[key]<0))throw Error('invalid-dimension-style-'+key);if(!Number.isInteger(d.precision)||d.precision<0||d.precision>8||!Object.hasOwn(units,d.units)||!['tick','closed','open','none'].includes(d.arrow))throw Error('invalid-dimension-style-format');if(d.format!=null&&(typeof d.format!=='string'||d.format.length>256))throw Error('invalid-dimension-style-format');if(d.textPosition!=null&&!['above','center'].includes(d.textPosition))throw Error('invalid-dimension-text-position');}return styles;}
 const get=name=>definitions().find(d=>d.name.toUpperCase()===String(name).toUpperCase())||null,style=o=>{const d=o?.styleName?get(o.styleName):null;return d&&o.styleOverrides?{...d,...o.styleOverrides}:d;};
 const geometryKey=o=>JSON.stringify(Object.fromEntries(['kind','p1','p2','offset','dimensionAngle','center','radius','labelPoint','vertex','ray1','ray2','textOverride','styleName','styleOverrides'].filter(k=>o[k]!=null).map(k=>[k,o[k]])));
 function geometry(o){const g=root.cadAnnotation2.geometry(o),d=style(o);if(!g||!d)return g;const s=d.overallScale||1,gap=(d.extensionOffset??.625)*s,beyond=(d.extensionBeyond??1.25)*s,textGap=(d.textGap??.625)*s;
  if(g.kind==='aligned'||g.kind==='linear'){const extension=(p,q)=>{const dx=q.x-p.x,dy=q.y-p.y,len=Math.hypot(dx,dy),u={x:len?dx/len:0,y:len?dy/len:1};return{a:{x:p.x+u.x*Math.min(gap,len),y:p.y+u.y*Math.min(gap,len)},b:{x:q.x+u.x*beyond,y:q.y+u.y*beyond}};},a=Math.atan2(g.d2.y-g.d1.y,g.d2.x-g.d1.x),n={x:-Math.sin(a),y:Math.cos(a)},shift=d.textPosition==='center'?0:textGap+d.textHeight*s/2;return{...g,labelPoint:{x:g.labelPoint.x+n.x*shift,y:g.labelPoint.y+n.y*shift},segments:[extension(g.p1,g.d1),extension(g.p2,g.d2),{a:g.d1,b:g.d2}]};}return g;
 }
 function label(o){const g=root.cadAnnotation2.geometry(o),d=style(o);if(!g)return'';let value=g.len??g.value??0,text;
  if(g.kind==='angular')text=root.cadUnits.formatAngle(value,{precision:d?.precision??1});
  else if(d){value*=d.lengthFactor||1;text=d.units==='ft-in'?root.cadUnits.formatLength(value,{system:'imperial',precision:d.precision}):(value/(units[d.units]||1)).toFixed(d.precision)+(d.showUnit?' '+d.units:'');if(g.kind==='radius')text='R '+text;else if(g.kind==='diameter')text='Ø '+text;}
  else{text=value.toFixed(1)+' mm';if(g.kind==='radius')text='R '+text;else if(g.kind==='diameter')text='Ø '+text;}
  const override=o.textOverride;if(override===' ')return'';const format=override&&override!=='<>'?override:d?.format||'<>';return format.replace(/<>/g,text);
 }
 function scene(o,{force=false}={}){const d=style(o)|| (force?defaults('Standard'):null),g=geometry(o);if(!d||!g)return null;const common={cadLayer:o.cadLayer||'0',color:o.color??null,linetype:o.linetype||'BYLAYER',lineweight:o.lineweight??null},items=[],add=(type,data)=>items.push({id:o.id+'/dim-'+items.length,type,blockOwnerId:o.blockOwnerId||o.id,...common,...data,...(data.color==='#111111'&&[d.dimensionColorIndex,d.extensionColorIndex,d.textColorIndex].includes(7)?{colorIndex:7,adaptiveColor:true}:{})}),color=v=>v==='BYBLOCK'?common.color:v||common.color,lineColor=color(d.dimensionColor),extensionColor=color(d.extensionColor),textColor=color(d.textColor),primary=g.kind==='angular'?g.segments.slice(0,2):g.segments;
  for(const [i,s]of primary.entries())add('cadLine',{...s,color:i<2&&['aligned','linear','angular'].includes(g.kind)?extensionColor:lineColor});if(g.kind==='angular')add('cadArc',{center:g.vertex,radius:g.radius,startAngle:g.startAngle,sweep:g.sweep,color:lineColor});
  const size=(d.arrowSize??2.5)*(d.overallScale||1),markers=g.kind==='aligned'||g.kind==='linear'?[[g.d1,g.d2],[g.d2,g.d1]]:g.kind==='radius'?[[g.edge,g.end]]:g.kind==='diameter'?[[g.edge,g.start],[g.start,g.edge]]:[[g.start,root.cadAnnotation2.pointAt(g.vertex,g.radius,g.startAngle+Math.sign(g.sweep)*.1)],[g.end,root.cadAnnotation2.pointAt(g.vertex,g.radius,g.startAngle+g.sweep-Math.sign(g.sweep)*.1)]];
  for(const [index,[tip,toward]]of markers.entries()){const angle=Math.atan2(toward.y-tip.y,toward.x-tip.x),c=Math.cos(angle),s=Math.sin(angle),block=index===0?d.arrowBlock1||d.arrowBlock:d.arrowBlock2||d.arrowBlock;if(block&&root.cadBlocks.get(block)){const b=root.cadBlocks.get(block),xsum=b.objects.filter(o=>o.a&&o.b).reduce((n,o)=>n+o.a.x+o.b.x,0);add('cadInsert',{blockName:block,matrix:root.cadBlocks.matrix(tip,angle*180/Math.PI+(xsum<0?180:0),size||1),color:lineColor});continue;}if(d.arrow==='none'||!size)continue;
   if(d.arrow==='tick'){const a=angle+Math.PI/4,q={x:Math.cos(a)*size,y:Math.sin(a)*size};add('cadLine',{a:{x:tip.x-q.x,y:tip.y-q.y},b:{x:tip.x+q.x,y:tip.y+q.y},color:lineColor});}
   else{const a={x:tip.x+c*size-s*size*.22,y:tip.y+s*size+c*size*.22},b={x:tip.x+c*size+s*size*.22,y:tip.y+s*size-c*size*.22};if(d.arrow==='open'){add('cadLine',{a:tip,b:a,color:lineColor});add('cadLine',{a:tip,b,color:lineColor});}else add('cadHatch',{points:[tip,a,b],pattern:'SOLID',opacity:1,color:lineColor});}
  }
  let rotation=d.textOrientation==='horizontal'||!['aligned','linear'].includes(g.kind)?0:Math.atan2(g.d2.y-g.d1.y,g.d2.x-g.d1.x)*180/Math.PI;if(rotation>90)rotation-=180;if(rotation<=-90)rotation+=180;
  const value=label(o);if(value)add('cadText',{point:g.labelPoint,text:value,height:d.textHeight*(d.overallScale||1),alignment:'center',verticalAlignment:2,rotation,color:textColor,textStyle:d.textStyle||'Standard'});return items;
 }
 function presentation(o){const d=o.styleName?get(o.styleName):null,DXF=root.architecturalDxf;if(!o.dxfPresentation||!o.dxf||o.dxf.geometryKey!==geometryKey(o)||d?.dxf&&d.dxf.signature!==DXF?.signature(d))return null;const source=blocks();if(blockSource!==source){blockSource=source;blockMap=new Map(source.map(b=>[b.name.toUpperCase(),b]));}const map=blockMap,seen=new Set();function safe(name,depth=0){const k=name.toUpperCase(),b=map.get(k);if(!b||seen.has(k)||depth>32)return false;seen.add(k);const ok=b.objects.every(q=>q.type!=='cadDimension'&&(q.type!=='cadInsert'||safe(q.blockName,depth+1)));seen.delete(k);return ok;}if(!safe(o.dxfPresentation))return null;const b=map.get(o.dxfPresentation.toUpperCase());return{...o,type:'cadInsert',blockName:b.name,matrix:root.cadBlocks.matrix(b.dxfBase||{x:0,y:0})};}
 root.cadDimensionStyles=Object.freeze({capability:'cad.dimstyle.v1',defaults,configure,validate,get,style,library:()=>definitions(),geometry,label,geometryKey,presentation,scene,unitFactor:u=>u==='ft-in'?25.4:units[u]||1});
})();
