/* Semantic DXF writer, with archived tables/classes/objects and opaque records retained.
 * Original handles are reused only for their original owner; copies get fresh handles. */
(() => {
 'use strict';const root=globalThis.PieniPlanModules=globalThis.PieniPlanModules||{},D=()=>root.architecturalDxf,clone=v=>JSON.parse(JSON.stringify(v)),rad=v=>v*Math.PI/180;
 function write({objects=[],blockDefinitions=[],layerDefinitions=[],dimensionStyles=[],archive=null,extraEntities=[]}={}){
  root.cadBlocks.validate(blockDefinitions,objects);const f=archive?.unitFactor||1,sections=clone(archive?.sections||[]),warnings=[],handles=new Set(),reserved=new Set(),owners=new Map(),definitions=blockDefinitions.slice(),get=(r,c,d=null)=>D().first(r,c,d),num=(r,c,d=0)=>D().num(r,c,d);let seed=1;
  const openName='PP_DIM_OPEN_ARROW';if(dimensionStyles.some(d=>d.arrow==='open'&&!d.arrowBlock)&&!definitions.some(d=>d.name.toUpperCase()===openName)){definitions.push({name:openName,base:{x:0,y:0},objects:[{id:'open-a',type:'cadLine',a:{x:0,y:0},b:{x:-f,y:.22*f},cadLayer:'0',color:'BYBLOCK'},{id:'open-b',type:'cadLine',a:{x:0,y:0},b:{x:-f,y:-.22*f},cadLayer:'0',color:'BYBLOCK'}]});}
  const reserve=data=>{for(const[c,v]of data||[])if(c===5||c===105){const n=parseInt(v,16);if(Number.isFinite(n)){handles.add(String(v).toUpperCase());seed=Math.max(seed,n+1);}}};for(const s of sections)reserve(s.pairs);for(const d of definitions){reserve(d.dxfHeader);reserve(d.dxfEnd);for(const o of d.objects)reserve(o.dxf?.raw||o.rawGroups);}for(const o of objects)reserve(o.dxf?.raw||o.rawGroups);for(const b of archive?.preservedBlocks||[]){reserve(b.rawHeader);reserve(b.rawEnd);for(const r of b.rawRecords)reserve(r);}
  const fresh=()=>{while(handles.has(seed.toString(16).toUpperCase()))seed++;const h=(seed++).toString(16).toUpperCase();handles.add(h);return h;},handle=(o,r)=>{const original=get(r||[],5);if(original&&(!o.dxf?.ownerId||o.dxf.ownerId===o.id)&&!reserved.has(original.toUpperCase())){reserved.add(original.toUpperCase());return original;}return fresh();};
  const xy=(p,code=10)=>[[code,p.x/f],[code+10,p.y/f],[code+20,0]],tablePairs=(type,name,body,h=fresh())=>[[0,type],[type==='DIMSTYLE'?105:5,h],[330,'0'],[100,'AcDbSymbolTableRecord'],[100,{LAYER:'AcDbLayerTableRecord',LTYPE:'AcDbLinetypeTableRecord',STYLE:'AcDbTextStyleTableRecord',DIMSTYLE:'AcDbDimStyleTableRecord',BLOCK_RECORD:'AcDbBlockTableRecord',APPID:'AcDbRegAppTableRecord'}[type]],[2,name],...body];
  const props=o=>{const r=o.dxf?.raw||[],out=[[8,o.cadLayer||'0']],color=typeof o.color==='string'&&/^#[0-9a-f]{3}$/i.test(o.color)?'#'+[...o.color.slice(1)].map(v=>v+v).join(''):o.color;if(color===D().properties(r).color&&r.length){if(get(r,62)!=null)out.push([62,get(r,62)]);if(get(r,420)!=null)out.push([420,get(r,420)]);}else if(color==='BYBLOCK')out.push([62,0]);else if(color==null||color==='BYLAYER')out.push([62,256]);else if(/^#[0-9a-f]{6}$/i.test(color))out.push([62,7],[420,parseInt(color.slice(1),16)]);else if(typeof color==='number')out.push([62,color]);out.push([6,o.linetype||'BYLAYER'],[370,o.lineweight==='BYBLOCK'?-2:typeof o.lineweight==='number'?Math.round(o.lineweight*100):-1]);if(get(r,48)!=null)out.push([48,get(r,48)]);return out;};
  const ownerOf=r=>{let braces=0;for(const[c,v]of r||[]){if(c===102){if(String(v).startsWith('{'))braces++;else if(v==='}')braces--;}if(c===330&&!braces)return v;}return null;};
  function extra(raw,omit){let braces=0;return(raw||[]).filter(([c,v])=>{if(c===102){if(String(v).startsWith('{'))braces++;else if(v==='}')braces--;return true;}return braces>0||c>=1000||!omit.has(c)&&![0,5,100,330,8,6,62,420,370,48].includes(c);});}
  function patternFamilyPairs(o,r,index){const oldAngle=num(r,52,0),oldScale=num(r,41,1)||1,base=o.hatchPatternTransform||root.cadBlocks.matrix(),v={x:Math.cos(rad(oldAngle)),y:Math.sin(rad(oldAngle))},a=Math.atan2(base.b*v.x+base.d*v.y,base.a*v.x+base.c*v.y)*180/Math.PI,scale=Math.hypot(base.a,base.b)||1,delta=(o.angle??oldAngle)-a,ratio=(o.patternScale??oldScale)/(oldScale*scale),m=root.cadBlocks.multiply(root.cadBlocks.matrix({x:0,y:0},delta,ratio),base),data=clone(r.slice(index).filter(p=>p[0]!==98&&p[0]!==10&&p[0]!==20));m.tx=base.tx;m.ty=base.ty;let dashScale=1;
   for(let i=0;i<data.length;i++){const [c,value]=data[i];if(c===53){const angle=rad(Number(value)),x=m.a*Math.cos(angle)+m.c*Math.sin(angle),y=m.b*Math.cos(angle)+m.d*Math.sin(angle);dashScale=Math.hypot(x,y);data[i][1]=Math.atan2(y,x)*180/Math.PI;}else if(c===43||c===45){const code=c===43?44:46,j=data.findIndex((p,k)=>k>i&&p[0]===code);if(j<0)continue;const x=Number(value)*f,y=Number(data[j][1])*f;data[i][1]=(m.a*x+m.c*y+(c===43?m.tx:0))/f;data[j][1]=(m.b*x+m.d*y+(c===43?m.ty:0))/f;}else if(c===49)data[i][1]=Number(value)*dashScale;}return data;
  }
  function clearedOverrides(raw){const out=[];let app=null;for(let i=0;i<raw.length;i++){const p=raw[i];if(p[0]===1001)app=p[1];if(app==='ACAD'&&p[0]===1000&&p[1]==='DSTYLE'&&raw[i+1]?.[0]===1002&&raw[i+1][1]==='{'){i++;let depth=1;while(depth&&++i<raw.length){if(raw[i][0]===1002)depth+=raw[i][1]==='{'?1:raw[i][1]==='}'?-1:0;}continue;}out.push(p);}return out.filter((p,i)=>p[0]!==1001||out[i+1]?.[0]>=1000&&out[i+1]?.[0]!==1001);}
  function safeExtras(o,raw,omit){let data=o.type==='cadDimension'&&o.styleOverrides===null?clearedOverrides(raw):raw;if(o.dxf?.ownerId&&o.dxf.ownerId!==o.id){const clean=[];let depth=0;for(const p of data){if(p[0]===102&&String(p[1]).startsWith('{ACAD_XDICTIONARY')){depth=1;warnings.push('Copied entity extension dictionary detached: '+o.id);continue;}if(depth){if(p[0]===102)depth+=String(p[1]).startsWith('{')?1:p[1]==='}'?-1:0;continue;}clean.push(p);}data=clean;}return extra(data,omit);}
  function entity(o,owner){if(o.type==='cadDxfRecord'){const r=clone(o.rawGroups);if(!r.length)throw Error('empty-preserved-dxf-record');return r;}
   const r=o.dxf?.raw||[],unchanged=o.dxf?.signature===D().signature(o)&&(!o.dxf.ownerId||o.dxf.ownerId===o.id);
   if(unchanged&&r.length&&get(r,5)){const q=clone(r),old=ownerOf(q);if(old&&old!==owner){let depth=0;for(const p of q){if(p[0]===102)depth+=String(p[1]).startsWith('{')?1:p[1]==='}'?-1:0;if(p[0]===330&&!depth){p[1]=owner;break;}}}return q;}
   let type,sub,body=[],omit=new Set([10,20,30,11,21,31,12,22,32,13,23,33,14,24,34,15,25,35,16,26,36,40,41,42,43,44,45,46,50,51,70,71,72,73,74,90,91,92,93,97,1,2,3,7,210,220,230]);
   if(o.type==='cadLine'){type='LINE';sub='AcDbLine';body=[...xy(o.a),...xy(o.b,11)];}
   else if(o.type==='cadPoint'){type='POINT';sub='AcDbPoint';body=xy(o.point);}
   else if(o.type==='cadXline'||o.type==='cadRay'){type=o.type==='cadXline'?'XLINE':'RAY';sub=type==='XLINE'?'AcDbXline':'AcDbRay';const dx=o.b.x-o.a.x,dy=o.b.y-o.a.y,len=Math.hypot(dx,dy);body=[...xy(o.a),[11,dx/len],[21,dy/len],[31,0]];}
   else if(o.type==='cadCircle'||o.type==='cadArc'){type=o.type==='cadCircle'?'CIRCLE':'ARC';sub='AcDbCircle';body=[...xy(o.center),[40,o.radius/f]];if(type==='ARC'){const a=o.sweep<0?o.startAngle+o.sweep:o.startAngle,b=o.sweep<0?o.startAngle:o.startAngle+o.sweep;body.push([100,'AcDbArc'],[50,(a%360+360)%360],[51,(b%360+360)%360]);}}
   else if(root.cadPolyline.is(o)){type='LWPOLYLINE';sub='AcDbPolyline';body=[[90,o.vertices.length],[70,o.closed?1:0]];for(const v of o.vertices)body.push([10,v.x/f],[20,v.y/f],[42,v.outgoing?.bulge||0]);}
   else if(o.type==='cadInsert'){type='INSERT';sub='AcDbBlockReference';const m=o.matrix,sx=Math.hypot(m.a,m.b),sy=(m.a*m.d-m.b*m.c)/sx;if(Math.abs(m.a*m.c+m.b*m.d)>1e-8*sx*Math.abs(sy))throw Error('sheared-insert-cannot-export');body=[[2,o.blockName],...xy({x:m.tx,y:m.ty}),[41,sx],[42,sy],[43,1],[50,Math.atan2(m.b,m.a)*180/Math.PI]];}
   else if(o.type==='cadText'){const m=o.mtext||String(o.text).includes('\n');type=m?'MTEXT':'TEXT';sub=m?'AcDbMText':'AcDbText';const text=m?String(o.text).replace(/\\/g,'\\\\').replace(/[{}]/g,v=>'\\'+v).replace(/\r?\n/g,'\\P'):String(o.text);const chunks=[];if(m){for(let i=0;i<text.length;i+=250)chunks.push(text.slice(i,i+250));}body=[...xy(o.point),[40,(o.height||180)/f],...(m?[...chunks.slice(0,-1).map(v=>[3,v]),[1,chunks.at(-1)||'']]:[[1,text]]),[50,o.rotation||0],[7,o.textStyle||'Standard']];if(m)body.push([41,(o.width||0)/f],[71,({left:1,center:2,right:3}[o.alignment]||1)+3*(o.verticalAlignment||0)]);else body.push([72,{left:0,center:1,right:2}[o.alignment]||0],...xy(o.point,11),[100,'AcDbText'],[73,o.verticalAlignment||0]);}
   else if(o.type==='cadHatch'){for(const c of [52,53,75,76,77,78,79,98,49])omit.add(c);type='HATCH';sub='AcDbHatch';const pattern=o.pattern||'ANSI31',loops=o.loops?.length?o.loops:[o.points],solid=pattern==='SOLID';body=[...xy({x:0,y:0}),[210,0],[220,0],[230,1],[2,pattern],[70,solid?1:0],[71,0],[91,loops.length]];for(const [i,loop]of loops.entries()){body.push([92,i===0?3:2],[72,0],[73,1],[93,loop.length]);for(const p of loop)body.push([10,p.x/f],[20,p.y/f]);body.push([97,0]);}body.push([75,0],[76,1]);if(!solid){const index=r.findIndex(p=>p[0]===78);if(index>=0&&get(r,2)===pattern){body.push([52,o.angle??num(r,52,45)],[41,o.patternScale||num(r,41,1)],[77,num(r,77)],...patternFamilyPairs(o,r,index));}else{const spacing=(o.spacingWorld||160)/f,angles=pattern==='CROSS'?[o.angle??45,(o.angle??45)+90]:[o.angle??45];body.push([52,o.angle??45],[41,o.patternScale||1],[77,0],[78,angles.length]);for(const angle of angles)body.push([53,angle],[43,0],[44,0],[45,-Math.sin(rad(angle))*spacing],[46,Math.cos(rad(angle))*spacing],[79,0]);}body.push([98,0]);}}
   else if(o.type==='cadLeader'){type='LEADER';sub='AcDbLeader';body=[[3,o.styleName||'Standard'],[71,1],[72,0],[73,3],[74,0],[75,0],[76,o.points.length],[40,(o.height||140)/f],[41,0]];for(const p of o.points)body.push(...xy(p));}
   else if(o.type==='cadDimension'){type='DIMENSION';sub='AcDbDimension';const g=root.cadDimensionStyles?.geometry?.(o)||root.cadAnnotation2.geometry(o);if(!g)throw Error('invalid-dimension');const kind=o.kind||'aligned',dimtype={linear:0,aligned:1,angular:5,radius:4,diameter:3}[kind];let n=1,name;do{name='*PPD'+n++;}while(definitions.some(d=>d.name.toUpperCase()===name.toUpperCase()));const dimStyle=root.cadDimensionStyles?.style?.(o),height=dimStyle?dimStyle.textHeight*(dimStyle.overallScale||1):250,label=root.cadDimensionStyles?.label?.(o)||String(g.len??g.value??'');definitions.push({name,base:{x:0,y:0},objects:root.cadDimensionStyles?.scene?.(o,{force:true})||[...g.segments.map((seg,i)=>({id:o.id+'-dimline-'+i,type:'cadLine',cadLayer:'0',color:'BYBLOCK',a:seg.a,b:seg.b})),{id:o.id+'-dimtext',type:'cadText',cadLayer:'0',color:'BYBLOCK',point:g.labelPoint,text:label,height,alignment:'center',rotation:0}]});body=[[2,name],[3,o.styleName||'Standard'],[70,dimtype+32],...xy(g.labelPoint,11),[1,o.textOverride??'<>']];if(kind==='aligned'||kind==='linear')body.push(...xy(g.d2),[100,'AcDbAlignedDimension'],...xy(o.p1,13),...xy(o.p2,14),...(kind==='linear'?[[100,'AcDbRotatedDimension'],[50,o.dimensionAngle]]:[]));else if(kind==='radius'||kind==='diameter')body.push(...xy(kind==='radius'?o.center:{x:2*o.center.x-g.edge.x,y:2*o.center.y-g.edge.y}),[100,kind==='radius'?'AcDbRadialDimension':'AcDbDiametricDimension'],...xy(g.edge,15),[40,0]);else body.push(...xy(g.start),[100,'AcDb3PointAngularDimension'],...xy(o.ray1,13),...xy(o.ray2,14),...xy(o.vertex,15));}
   else throw Error('unsupported-native-dxf-export:'+o.type);
   return[[0,type],[5,handle(o,r)],[330,owner],[100,'AcDbEntity'],...props(o),[100,sub],...body,...safeExtras(o,r,omit)];
  }
  // Entity serialization may allocate dimension presentation definitions. Stage it before tables.
  let tables=sections.find(s=>s.name==='TABLES')?.pairs||[],tableRecords=D().records(tables);for(const r of tableRecords)if(get(r,0)==='BLOCK_RECORD')owners.set(String(get(r,2)).toUpperCase(),get(r,5));
  const modelName=[...owners.keys()].find(n=>n==='*MODEL_SPACE')||'*MODEL_SPACE',paperName='*PAPER_SPACE';for(const name of [modelName,paperName,...definitions.map(d=>d.name),...(archive?.preservedBlocks||[]).map(d=>d.name)])if(!owners.has(name.toUpperCase()))owners.set(name.toUpperCase(),fresh());
  const modelOwner=owners.get(modelName),entityData=objects.flatMap(o=>entity(o,modelOwner));for(const d of definitions)if(!owners.has(d.name.toUpperCase()))owners.set(d.name.toUpperCase(),fresh());
  // Nested newly generated dimensions can add definitions while walking this array.
  const blocks=[];for(const name of [modelName,paperName])blocks.push([0,'BLOCK'],[5,fresh()],[330,owners.get(name)],[100,'AcDbEntity'],[8,'0'],[100,'AcDbBlockBegin'],[2,name],[70,0],...xy({x:0,y:0}),[3,name],[1,''],[0,'ENDBLK'],[5,fresh()],[330,owners.get(name)],[100,'AcDbEntity'],[8,'0'],[100,'AcDbBlockEnd']);
  for(const d of definitions){if(!owners.has(d.name.toUpperCase()))owners.set(d.name.toUpperCase(),fresh());const owner=owners.get(d.name.toUpperCase()),base=d.dxfBase||{x:0,y:0},header=d.dxfHeader;blocks.push([0,'BLOCK'],[5,header?get(header,5)||fresh():fresh()],[330,owner],[100,'AcDbEntity'],[8,get(header||[],8,'0')],[100,'AcDbBlockBegin'],[2,d.name],[70,num(header||[],70)],[10,base.x/f],[20,base.y/f],[30,0],[3,d.name],[1,get(header||[],1,'')]);for(const o of d.objects){const q=base.x||base.y?root.cadBlocks.transformLeaf(o,root.cadBlocks.matrix(base),{approximate:false}):o;blocks.push(...entity(q,owner));}blocks.push([0,'ENDBLK'],[5,d.dxfEnd?get(d.dxfEnd,5)||fresh():fresh()],[330,owner],[100,'AcDbEntity'],[8,'0'],[100,'AcDbBlockEnd']);}
  for(const b of archive?.preservedBlocks||[]){blocks.push(...clone(b.rawHeader),...b.rawRecords.flatMap(clone),...(b.rawEnd?clone(b.rawEnd):[[0,'ENDBLK']]));warnings.push('Preserved unavailable block: '+b.name);}
  function updateTable(type,entries){let start=tables.findIndex((p,i)=>p[0]===0&&p[1]==='TABLE'&&tables[i+1]?.[0]===2&&tables[i+1][1]===type),end=start<0?-1:tables.findIndex((p,i)=>i>start&&p[0]===0&&p[1]==='ENDTAB');const existing=start<0?[]:D().records(tables.slice(start,end)),keep=existing.filter(r=>get(r,0)!=='TABLE'&&!entries.has(String(get(r,2)).toUpperCase()));const body=[...keep,...entries.values()];const tableHandle=existing[0]?get(existing[0],5)||fresh():fresh();for(const r of body){const owner=r.find(p=>p[0]===330);if(owner)owner[1]=tableHandle;}const head=existing[0]?clone(existing[0]):[[0,'TABLE'],[2,type],[5,tableHandle],[330,'0'],[100,'AcDbSymbolTable'],...(type==='DIMSTYLE'?[[100,'AcDbDimStyleTable']]:[])];const count=head.find(p=>p[0]===70);if(count)count[1]=body.length;else head.push([70,body.length]);const data=[...head,...body.flat(),[0,'ENDTAB']];if(start<0)tables.push(...data);else tables.splice(start,end-start+1,...data);}
  const layerMap=new Map(layerDefinitions.map(l=>[l.name,{...l}]));for(const o of [...objects,...definitions.flatMap(d=>d.objects)])if(!layerMap.has(o.cadLayer||'0'))layerMap.set(o.cadLayer||'0',{name:o.cadLayer||'0'});if(!layerMap.has('0'))layerMap.set('0',{name:'0'});const layers=new Map();for(const [name,l]of layerMap){const r=l.dxf?.raw||tableRecords.find(r=>get(r,0)==='LAYER'&&get(r,2)===name)||[],color=l.color&&/^#[0-9a-f]{6}$/i.test(l.color)?parseInt(l.color.slice(1),16):null;if(l.dxf?.signature===D().signature(l)){layers.set(name.toUpperCase(),clone(r));continue;}layers.set(name.toUpperCase(),tablePairs('LAYER',name,[[70,l.locked?4:0],[62,(l.visible===false?-1:1)*Math.abs(Number(get(r,62,7)))],...(color!=null&&(get(r,420)!=null||l.color!==D().properties(r).color)?[[420,color]]:[]),[6,l.linetype||'CONTINUOUS'],[370,typeof l.lineweight==='number'?Math.round(l.lineweight*100):-3],[290,l.printable===false?0:1]],get(r,5)||fresh()));}updateTable('LAYER',layers);
  const ltypes=new Map(),ltNames=new Set(['CONTINUOUS',...layerMap.values()].map(l=>typeof l==='string'?l:l.linetype||'CONTINUOUS'));for(const o of objects)if(o.linetype&&!['BYLAYER','BYBLOCK'].includes(o.linetype))ltNames.add(o.linetype);for(const name of ltNames)if(!tableRecords.some(r=>get(r,0)==='LTYPE'&&get(r,2)===name)){const pattern=name==='DASHED'?[12,-6]:name==='CENTER'?[24,-6,2,-6]:name==='DOTTED'?[0,-4]:[];ltypes.set(name.toUpperCase(),tablePairs('LTYPE',name,[[70,0],[3,name],[72,65],[73,pattern.length],[40,pattern.reduce((n,v)=>n+Math.abs(v),0)],...pattern.flatMap(v=>[[49,v],[74,0]])]));}updateTable('LTYPE',ltypes);
  const styles=new Map();for(const name of new Set(['Standard',...objects.filter(o=>o.type==='cadText').map(o=>o.textStyle||'Standard'),...definitions.flatMap(d=>d.objects).filter(o=>o.type==='cadText').map(o=>o.textStyle||'Standard')]))if(!tableRecords.some(r=>get(r,0)==='STYLE'&&String(get(r,2)).toUpperCase()===name.toUpperCase()))styles.set(name.toUpperCase(),tablePairs('STYLE',name,[[70,0],[40,0],[41,1],[50,0],[71,0],[42,2.5],[3,'txt'],[4,'']]));updateTable('STYLE',styles);
  const dims=new Map(),dimList=dimensionStyles.length?dimensionStyles:[{name:'Standard',textHeight:250,arrowSize:250,overallScale:1,precision:1}];for(const d of dimList){const r=d.dxf?.raw||tableRecords.find(r=>get(r,0)==='DIMSTYLE'&&get(r,2)===d.name)||[];if(d.dxf?.signature===D().signature(d)){dims.set(d.name.toUpperCase(),clone(r));continue;}dims.set(d.name.toUpperCase(),tablePairs('DIMSTYLE',d.name,[[70,0],[3,(d.format||'<>')+(d.showUnit&&d.units!=='ft-in'?' '+d.units:'')],[40,d.overallScale||1],[41,d.arrow==='none'?0:(d.arrowSize??250)/f],[42,(d.extensionOffset??60)/f],[44,(d.extensionBeyond??120)/f],[140,(d.textHeight||250)/f],[147,(d.textGap??60)/f],[144,(d.lengthFactor||1)*f/(root.cadDimensionStyles?.unitFactor?.(d.units)||1)],[142,d.arrow==='tick'?(d.arrowSize||0)/f:0],[77,d.textPosition==='center'?0:1],[73,d.textOrientation==='horizontal'?1:0],[74,d.textOrientation==='horizontal'?1:0],[271,d.precision??1],[277,d.units==='ft-in'?3:2],...[[342,d.arrowBlock|| (d.arrow==='open'?openName:null)],[343,d.arrowBlock1],[344,d.arrowBlock2]].filter(([,name])=>name&&owners.has(name.toUpperCase())).map(([c,name])=>[c,owners.get(name.toUpperCase())]),[173,d.arrowBlock1||d.arrowBlock2?1:0],...(get(r,340)?[]:[[340,get(D().records(tables).find(r=>get(r,0)==='STYLE'&&String(get(r,2)).toUpperCase()===(d.textStyle||'Standard').toUpperCase())||[],5,'0')]]),...extra(r,new Set([105,2,3,70,40,41,42,44,140,147,144,142,77,73,74,271,277,342,343,344,173]))],get(r,105)||fresh()));}updateTable('DIMSTYLE',dims);
  const blockRecords=new Map();for(const [name,h]of owners){const r=tableRecords.find(r=>get(r,0)==='BLOCK_RECORD'&&String(get(r,2)).toUpperCase()===name);blockRecords.set(name,r||tablePairs('BLOCK_RECORD',name,[[70,0],[280,1],[281,0]],h));}updateTable('BLOCK_RECORD',blockRecords);
  let header=sections.find(s=>s.name==='HEADER')?.pairs||[];const variable=(name,code,value)=>{const start=header.findIndex(p=>p[0]===9&&p[1]===name);if(start<0)header.push([9,name],[code,value]);else{let end=start+1;while(end<header.length&&header[end][0]!==9)end++;header.splice(start,end-start,[9,name],[code,value]);}};variable('$ACADVER',1,archive&&Number(String(archive.version).slice(2))>=1021?archive.version:'AC1021');variable('$INSUNITS',70,archive?.unitCode??4);variable('$DWGCODEPAGE',3,'UTF-8');variable('$HANDSEED',5,seed.toString(16).toUpperCase());
  const output=[{name:'HEADER',pairs:header},...sections.filter(s=>s.name==='CLASSES'),{name:'TABLES',pairs:tables},{name:'BLOCKS',pairs:blocks},{name:'ENTITIES',pairs:[...entityData,...extraEntities]},...sections.filter(s=>!['HEADER','CLASSES','TABLES'].includes(s.name))],flat=output.flatMap(s=>[[0,'SECTION'],[2,s.name],...s.pairs,[0,'ENDSEC']]);flat.push([0,'EOF']);return{text:flat.map(([c,v])=>String(c)+'\n'+String(v)).join('\n')+'\n',warnings,entityCount:objects.length,definitionCount:definitions.length};
 }
 root.architecturalDxfWriter=Object.freeze({write});
})();
