/* Native 2D DXF interchange. Specification-derived; no third-party runtime dependency.
 * Unsupported records are retained read-only, with explicit diagnostics. Import is pure. */
(() => {
 'use strict';const root=globalThis.PieniPlanModules=globalThis.PieniPlanModules||{},clone=v=>JSON.parse(JSON.stringify(v)),finite=Number.isFinite,rad=v=>v*Math.PI/180;
 const first=(pairs,c,d=null)=>pairs.find(p=>p[0]===c)?.[1]??d,num=(p,c,d=0)=>Number(first(p,c,d)),point=(p,c=10,f=1)=>({x:num(p,c)*f,y:num(p,c+10)*f}),all=(p,c)=>p.filter(q=>q[0]===c).map(q=>q[1]);
 function pairs(text){if(text.startsWith('AutoCAD Binary DXF'))throw Error('binary-dxf-not-supported');const lines=text.replace(/^\uFEFF/,'').split(/\r\n|\n|\r/);while(lines.length&&!lines.at(-1).trim())lines.pop();if(lines.length%2)throw Error('invalid-dxf-pair-count');const out=[];for(let i=0;i<lines.length;i+=2){const c=Number(lines[i].trim());if(!Number.isInteger(c)||c<0||c>1071)throw Error('invalid-dxf-group-code');out.push([c,lines[i+1]]);}return out;}
 function sections(data){const out=[];for(let i=0;i<data.length;i++)if(data[i][0]===0&&data[i][1].trim()==='SECTION'){if(data[i+1]?.[0]!==2)throw Error('invalid-dxf-section');const name=data[++i][1].trim(),body=[];while(++i<data.length&&!(data[i][0]===0&&data[i][1].trim()==='ENDSEC'))body.push(data[i]);if(i===data.length)throw Error('unterminated-dxf-section');out.push({name,pairs:body});}return out;}
 function records(data){const out=[];let current=null;for(const p of data){if(p[0]===0){current=[];out.push(current);}if(current)current.push(p);}const grouped=[];for(let i=0;i<out.length;i++){const r=out[i],type=first(r,0);if(type==='POLYLINE'){const q=r.slice();while(i+1<out.length&&['VERTEX','SEQEND'].includes(first(out[i+1],0))){const next=out[++i];q.push(...next);if(first(next,0)==='SEQEND')break;}grouped.push(q);}else if(type==='INSERT'&&num(r,66)===1){const q=r.slice();while(i+1<out.length&&['ATTRIB','SEQEND'].includes(first(out[i+1],0))){const next=out[++i];q.push(...next);if(first(next,0)==='SEQEND')break;}grouped.push(q);}else grouped.push(r);}return grouped;}
 function decode(buffer){const bytes=new Uint8Array(buffer),ascii=new TextDecoder('windows-1252').decode(bytes),ver=ascii.match(/\$ACADVER\s*\n\s*1\s*\n\s*(AC\d+)/)?.[1]||'AC1009',cp=ascii.match(/\$DWGCODEPAGE\s*\n\s*3\s*\n\s*([^\r\n]+)/)?.[1]?.trim(),encoding=Number(ver.slice(2))>=1021?'utf-8':/949|KOREAN/i.test(cp||'')?'euc-kr':/932/i.test(cp||'')?'shift_jis':/936/i.test(cp||'')?'gbk':/950/i.test(cp||'')?'big5':'windows-1252';return new TextDecoder(encoding).decode(bytes);}
 function textValue(value,mtext=false){let s=String(value||'').replace(/\\U\+([0-9a-f]{4})/gi,(_,h)=>String.fromCharCode(parseInt(h,16))).replace(/%%d/gi,'°').replace(/%%p/gi,'±').replace(/%%c/gi,'Ø');if(mtext)s=s.replace(/\\\\/g,'\uE000').replace(/\\\{/g,'\uE001').replace(/\\\}/g,'\uE002').replace(/\\P/g,'\n').replace(/\\~/g,' ').replace(/\\[ACFHQTWacfhqtw][^;]*;/g,'').replace(/\\S([^;]+);/g,(_,v)=>v.replace(/[\^#]/g,'/')).replace(/[{}]/g,'').replace(/\\[LlOoKk]/g,'').replace(/\uE000/g,'\\').replace(/\uE001/g,'{').replace(/\uE002/g,'}');return s;}
 function aci(index){const base=['#000000','#ff0000','#ffff00','#00ff00','#00ffff','#0000ff','#ff00ff','#111111','#808080','#c0c0c0'];if(index<10)return base[Math.abs(index)]||'#111111';if(index>=250){const v=[51,80,105,130,190,255][Math.min(5,index-250)];return'#'+v.toString(16).padStart(2,'0').repeat(3);}const h=Math.floor((index-10)/10)*15/60,v=[1,1,.65,.65,.5,.5,.3,.3,.15,.15][(index-10)%10],s=index%2?.5:1,k=n=>(n+h*2)%12,f=n=>v-v*s*Math.max(0,Math.min(k(n)-3,9-k(n),1)),rgb=[f(0),f(8),f(4)];return'#'+rgb.map(x=>Math.round(x*255).toString(16).padStart(2,'0')).join('');}
 function properties(r){const color=num(r,62,256),trueColor=first(r,420),weight=num(r,370,-1);return{cadLayer:first(r,8,'0'),colorIndex:color,color:trueColor!=null?'#'+Number(trueColor).toString(16).padStart(6,'0'):color===0?'BYBLOCK':Math.abs(color)===256?'BYLAYER':aci(Math.abs(color)),linetype:first(r,6,'BYLAYER'),lineweight:weight===-2?'BYBLOCK':weight<0?'BYLAYER':weight/100};}
 const units=new Map([[0,1],[1,25.4],[2,304.8],[3,1609344],[4,1],[5,10],[6,1000],[7,1e6],[8,.0000254],[9,.0254],[10,914.4],[11,1e-7],[12,1e-6],[13,.001],[14,100],[15,10000],[16,100000],[17,1e12],[21,304.8006096012192]]);
 function signature(o){const q={...o};delete q.id;delete q.dxf;delete q.blockOwnerId;delete q.selected;return JSON.stringify(q);}
 function parse(text){const ss=sections(pairs(text)),header=ss.find(s=>s.name==='HEADER')?.pairs||[],getHeader=(name,d)=>{const i=header.findIndex(p=>p[0]===9&&p[1]===name);return i<0?d:header[i+1]?.[1]??d;},unitCode=Number(getHeader('$INSUNITS',0)),f=units.get(unitCode);if(!f)throw Error('unsupported-dxf-units');let seq=0;const uid=type=>type+'-dxf-'+(++seq),diagnostics=[],warnings=new Set(),tables=records(ss.find(s=>s.name==='TABLES')?.pairs||[]),layerDefinitions=[],dimensionStyles=[],blockDefinitions=[],rawBlocks=[],model=records(ss.find(s=>s.name==='ENTITIES')?.pairs||[]),counts={};
  const warn=(type,reason)=>{diagnostics.push({type,reason,handling:'read-only-preserved'});};
  const raw=(r,reason,preview=[])=>{const type=first(r,0);warn(type,reason);return{id:uid('cadDxfRecord'),type:'cadDxfRecord',...properties(r),readonly:true,recordType:type,rawGroups:clone(r),preview,reason};};
  for(const r of tables){const type=first(r,0);if(type==='LAYER'){const props=properties(r),flags=num(r,70);layerDefinitions.push({name:first(r,2,'0'),colorIndex:Math.abs(num(r,62,7)),color:props.color==='BYLAYER'?aci(Math.abs(num(r,62,7))):props.color,linetype:first(r,6,'CONTINUOUS'),lineweight:num(r,370,-1)<0?'DEFAULT':num(r,370)/100,locked:Boolean(flags&4),printable:num(r,290,1)!==0,visible:num(r,62,7)>=0&&!(flags&1),dxf:{raw:clone(r)}});}else if(type==='DIMSTYLE'){dimensionStyles.push({name:first(r,2,'Standard'),textHeight:num(r,140,2.5)*f,arrowSize:num(r,41,2.5)*f,extensionOffset:num(r,42,.625)*f,extensionBeyond:num(r,44,1.25)*f,textGap:num(r,147,.625)*f,overallScale:num(r,40,1)||1,precision:num(r,271,2),units:f===25.4?'in':f===304.8?'ft':f===1000?'m':f===10?'cm':'mm',lengthFactor:num(r,144,1)||1,arrow:num(r,142)?'tick':'closed',textPosition:num(r,77)?'above':'center',textOrientation:num(r,73)||num(r,74)?'horizontal':'aligned',dimensionColorIndex:num(r,176,0),extensionColorIndex:num(r,177,0),textColorIndex:num(r,178,0),dimensionColor:num(r,176,0)?aci(num(r,176)):'BYBLOCK',extensionColor:num(r,177,0)?aci(num(r,177)):'BYBLOCK',textColor:num(r,178,0)?aci(num(r,178)):'BYBLOCK',format:first(r,3,'<>'),dxf:{raw:clone(r)}});}}
  const styleNamesByHandle=new Map(tables.filter(r=>first(r,0)==='STYLE').map(r=>[first(r,5),first(r,2)])),blockNamesByHandle=new Map(tables.filter(r=>first(r,0)==='BLOCK_RECORD').map(r=>[first(r,5),first(r,2)]));
  for(const d of dimensionStyles){d.readonly=d.name.includes('|');const r=d.dxf.raw;const suffix=String(first(r,3,'')).match(/\s(mm|cm|m|in|ft)$/);if(suffix){d.units=suffix[1];d.showUnit=true;d.format=String(first(r,3)).slice(0,-suffix[0].length);d.lengthFactor=(num(r,144,1)||1)*({mm:1,cm:10,m:1000,in:25.4,ft:304.8}[d.units])/f;}else d.showUnit=false;d.textStyle=styleNamesByHandle.get(first(r,340))||'Standard';d.arrowBlock=blockNamesByHandle.get(first(r,342));d.arrowBlock1=num(r,173)?blockNamesByHandle.get(first(r,343)):undefined;d.arrowBlock2=num(r,173)?blockNamesByHandle.get(first(r,344)):undefined;if([d.arrowBlock,d.arrowBlock1,d.arrowBlock2].some(n=>/ARCHTICK|OBLIQUE/i.test(n||'')))d.arrow='tick';if([d.arrowBlock,d.arrowBlock1,d.arrowBlock2].some(n=>/^_OPEN|PP_DIM_OPEN_ARROW/i.test(n||'')))d.arrow='open';if(!num(r,142)&&!num(r,41))d.arrow='none';if(num(r,142))d.arrowSize=num(r,142)*f;if(num(r,277)===3||num(r,277)===4){d.units='ft-in';d.lengthFactor=num(r,144,1)*25.4/f;}}
  function dimensionOverrides(r){const start=r.findIndex(p=>p[0]===1000&&p[1]==='DSTYLE');if(start<0)return null;const out={},m={40:'overallScale',41:'arrowSize',42:'extensionOffset',44:'extensionBeyond',140:'textHeight',147:'textGap',271:'precision'};for(let i=start+1;i<r.length;i++){if(r[i][0]===1002&&r[i][1]==='}')break;if(r[i][0]!==1070||!r[i+1])continue;const c=Number(r[i][1]),v=r[++i][1];if(m[c])out[m[c]]=Number(v)*([41,42,44,140,147].includes(c)?f:1);else if(c===142&&Number(v)){out.arrow='tick';out.arrowSize=Number(v)*f;}else if(c===77)out.textPosition=Number(v)?'above':'center';else if(c===73||c===74)out.textOrientation=Number(v)?'horizontal':'aligned';else if(c===176||c===177||c===178){const key={176:'dimensionColor',177:'extensionColor',178:'textColor'}[c];out[key]=Number(v)?aci(Number(v)):'BYBLOCK';out[key+'Index']=Number(v);}else if(c===340)out.textStyle=styleNamesByHandle.get(v)||'Standard';else if(c===342||c===343||c===344)out[{342:'arrowBlock',343:'arrowBlock1',344:'arrowBlock2'}[c]]=blockNamesByHandle.get(v);else if(c===3)out.format=v;else if(c===144)out.lengthFactor=Number(v);}
   if([out.arrowBlock,out.arrowBlock1,out.arrowBlock2].some(n=>/ARCHTICK|OBLIQUE/i.test(n||'')))out.arrow='tick';return out;
  }
  for(const d of [...layerDefinitions,...dimensionStyles])d.dxf.signature=signature(d);
  function entity(r){const type=first(r,0),props=properties(r),make=(kind,data)=>{for(const key of ['a','b','point','center'])if(data[key]&&![data[key].x,data[key].y].every(finite))throw Error('non-finite-coordinate');for(const ps of [data.vertices,data.points,...(data.loops||[])])if(ps&&(!Array.isArray(ps)||!ps.every(p=>finite(p.x)&&finite(p.y))))throw Error('non-finite-coordinate');if(['cadXline','cadRay'].includes(kind)&&Math.hypot(data.b.x-data.a.x,data.b.y-data.a.y)<1e-9)throw Error('zero-construction-direction');if(data.radius!=null&&(!finite(data.radius)||data.radius<=0))throw Error('invalid-radius');if(data.height!=null&&(!finite(data.height)||data.height<=0))throw Error('invalid-text-height');const o={id:uid(kind),type:kind,...props,...data,source:'DXF'};o.dxf={raw:clone(r),ownerId:o.id,signature:signature(o)};return o;};
   if(num(r,67)!==0)return raw(r,'paper-space-not-editable');
   if(num(r,210)!==0||num(r,220)!==0||num(r,230,1)!==1||[30,31,32,33,34,35,36,38,39].some(c=>Math.abs(num(r,c))>1e-7))return raw(r,'non-planar-ocs-or-elevation');
   try{
    if(type==='POINT')return make('cadPoint',{point:point(r,10,f)});
    if(type==='LINE'){const o=make('cadLine',{a:point(r,10,f),b:point(r,11,f)}),cells=[o.a.x,o.a.y,o.b.x,o.b.y].map(v=>Math.floor(v/1000)),n=(Math.abs(cells[0]-cells[2])+1)*(Math.abs(cells[1]-cells[3])+1);return cells.some(v=>!Number.isSafeInteger(v))||n>100000?raw(r,'line-grid-budget-preserved',[o]):o;}
    if(type==='XLINE'||type==='RAY'){const a=point(r,10,f),v=point(r,11,f);return make(type==='XLINE'?'cadXline':'cadRay',{a,b:{x:a.x+v.x,y:a.y+v.y},mode:type==='XLINE'?'line':'ray'});}
    if(type==='CIRCLE')return make('cadCircle',{center:point(r,10,f),radius:num(r,40)*f});
    if(type==='ARC'){const a=num(r,50),s=((num(r,51)-a)%360+360)%360;return make('cadArc',{center:point(r,10,f),radius:num(r,40)*f,startAngle:a,sweep:s||360});}
    if(type==='TEXT'||type==='MTEXT'){const m=type==='MTEXT',attach=num(r,71,1),h=num(r,72),v=num(r,73),anchor=!m&&(h||v)&&first(r,11)!=null?point(r,11,f):point(r,10,f),alignment=m?[1,4,7].includes(attach)?'left':[2,5,8].includes(attach)?'center':'right':h===1?'center':h===2?'right':'left';if(!m&&[3,4,5].includes(h))warnings.add('TEXT fit/aligned uses a visual approximation; original record is retained.');if(first(r,7,'Standard').toUpperCase()!=='STANDARD'||!m&&(num(r,41,1)!==1||num(r,51)||num(r,71)))warnings.add('TEXT/MTEXT uses the bundled display font; source font, width-factor, oblique/mirror and rich formatting are retained in DXF records, with visual approximations.');const rotation=first(r,50)!=null?num(r,50):m&&first(r,11)!=null?Math.atan2(num(r,21),num(r,11))*180/Math.PI:0;return make('cadText',{point:anchor,text:textValue(m?[...all(r,3),first(r,1,'')].join(''):first(r,1,''),m),height:num(r,40,2.5)*f,rotation,alignment,width:m?Math.max(0,num(r,41)*f):0,mtext:m,verticalAlignment:m?Math.floor((attach-1)/3):v,textStyle:first(r,7,'Standard')});}
    if(type==='LWPOLYLINE'||type==='POLYLINE'){let vertices=[],closed=Boolean(num(r,70)&1);if(type==='POLYLINE'){if(num(r,70)&(8|16|64))return raw(r,'3d-or-mesh-polyline');const start=r.findIndex((p,i)=>i&&p[0]===0&&p[1]==='VERTEX'),rs=records(r.slice(start));vertices=rs.filter(q=>first(q,0)==='VERTEX').map(q=>({id:uid('cadVertex'),...point(q,10,f),outgoing:{id:uid('cadEdge'),bulge:num(q,42)}}));if(num(r,70)&(2|4))warnings.add('Legacy fitted POLYLINE control vertices are preserved; native editing uses stored segments.');}else{let current;for(const[c,v]of r){if(c===10){current={id:uid('cadVertex'),x:Number(v)*f,y:0,outgoing:{id:uid('cadEdge'),bulge:0}};vertices.push(current);}else if(current&&c===20)current.y=Number(v)*f;else if(current&&c===42)current.outgoing.bulge=Number(v);}}if(!closed&&vertices.length)delete vertices.at(-1).outgoing;const o=make('cadPolyline',{vertices,closed});try{root.cadPolyline.validate(o);}catch(e){const edges=[];for(let i=0;i<vertices.length-(closed?0:1);i++){const a=vertices[i],b=vertices[(i+1)%vertices.length];if(Math.hypot(a.x-b.x,a.y-b.y)<1e-7)continue;const edge=root.cadPolyline.deriveEdge(a,b,a.outgoing?.bulge||0);edges.push({...edge,id:uid('cadPreview'),cadLayer:props.cadLayer});}return raw(r,'polyline-topology-preserved:'+e.message,edges);}return o;}
    if(type==='INSERT'){if(num(r,66)||num(r,70,1)!==1||num(r,71,1)!==1)return raw(r,'attributes-or-array-insert-preserved');return make('cadInsert',{blockName:first(r,2,''),matrix:root.cadBlocks.matrix(point(r,10,f),num(r,50),num(r,41,1),num(r,42,1))});}
    if(type==='DIMENSION'){const kind=num(r,70)&15,definition=point(r,10,f),p1=point(r,13,f),p2=point(r,14,f),label=first(r,11)!=null?point(r,11,f):null;let data;
     if(kind===0||kind===1){const a=kind===0?num(r,50):Math.atan2(p2.y-p1.y,p2.x-p1.x)*180/Math.PI,n={x:-Math.sin(rad(a)),y:Math.cos(rad(a))};data={kind:kind===0?'linear':'aligned',p1,p2,offset:(definition.x-p1.x)*n.x+(definition.y-p1.y)*n.y,...(kind===0?{dimensionAngle:a}:{})};}
     else if(kind===3||kind===4){const edge=point(r,15,f),center=kind===4?definition:{x:(definition.x+edge.x)/2,y:(definition.y+edge.y)/2};data={kind:kind===3?'diameter':'radius',center,radius:Math.hypot(edge.x-center.x,edge.y-center.y),labelPoint:label||edge};}
     else if(kind===5){const vertex=point(r,15,f);data={kind:'angular',vertex,ray1:p1,ray2:p2,radius:Math.hypot(definition.x-vertex.x,definition.y-vertex.y),...(label?{labelPoint:label}:{})};}
     else if(kind===2){const q=point(r,15,f),vertex=root.geometryQuery.intersections({a:p1,b:p2,mode:'line'},{a:definition,b:q,mode:'line'})[0],arc=point(r,16,f);if(!vertex)return raw(r,'parallel-angular-dimension');data={kind:'angular',vertex:{x:vertex.x,y:vertex.y},ray1:Math.hypot(p2.x-vertex.x,p2.y-vertex.y)>1e-7?p2:p1,ray2:Math.hypot(q.x-vertex.x,q.y-vertex.y)>1e-7?q:definition,radius:Math.hypot(arc.x-vertex.x,arc.y-vertex.y),...(label?{labelPoint:label}:{})};}
     else return raw(r,'unsupported-dimension-type-'+kind);
     const o=make('cadDimension',{...data,styleName:first(r,3,'Standard'),textOverride:textValue(first(r,1,'<>')),styleOverrides:dimensionOverrides(r),dxfPresentation:first(r,2,null)});o.segments=root.cadAnnotation2.segments(o);if(!o.segments.length)return raw(r,'invalid-dimension-geometry');o.dxf.signature=signature(o);o.dxf.geometryKey=root.cadDimensionStyles?.geometryKey(o);return o;
    }
    if(type==='HATCH'){const loops=[];let i=r.findIndex(p=>p[0]===91);const n=num(r,91);if(i<0||n<1||n>10000)return raw(r,'invalid-hatch-boundary');for(let j=0;j<n;j++){while(++i<r.length&&r[i][0]!==92){}if(i===r.length)return raw(r,'invalid-hatch-path');const flags=Number(r[i][1]);let count=0,loop=[],current=null;
      if(flags&2){while(++i<r.length&&r[i][0]!==97){const[c,v]=r[i];if(c===93)count=Number(v);if(c===10){current={x:Number(v)*f,y:0};loop.push(current);}else if(c===20&&current)current.y=Number(v)*f;else if(c===42&&Number(v)!==0)return raw(r,'curved-hatch-boundary-preserved');}if(loop.length!==count||loop.length<3)return raw(r,'invalid-hatch-loop');}
      else{const edges=[];let edge=[];while(++i<r.length&&r[i][0]!==97){if(r[i][0]===93)count=Number(r[i][1]);else if(r[i][0]===72){if(edge.length)edges.push(edge);edge=[r[i]];}else if(edge.length)edge.push(r[i]);}if(edge.length)edges.push(edge);if(edges.length!==count||edges.some(e=>Number(first(e,72))!==1))return raw(r,'curved-hatch-edge-boundary-preserved');for(const e of edges){const a=point(e,10,f),b=point(e,11,f);if(loop.length&&Math.hypot(loop.at(-1).x-a.x,loop.at(-1).y-a.y)>1e-6)return raw(r,'unordered-hatch-edge-boundary-preserved');if(!loop.length)loop.push(a);loop.push(b);}if(loop.length>1&&Math.hypot(loop[0].x-loop.at(-1).x,loop[0].y-loop.at(-1).y)<1e-6)loop.pop();if(loop.length<3)return raw(r,'invalid-hatch-edge-loop');}
      const sources=Number(r[i]?.[1]||0);i+=sources;loops.push(loop);}if(first(r,2,'SOLID')!=='SOLID')warnings.add('Imported HATCH boundaries, holes and pattern records are retained; display uses a generic basic pattern rather than every DXF pattern family.');return make('cadHatch',{points:loops[0],loops,pattern:first(r,2,'SOLID'),angle:num(r,52,45),patternScale:num(r,41,1),spacingPx:16,sourceBoundaryId:null,opacity:num(r,70)?1:.14});}
    if(type==='LEADER'){const ps=[];let q;for(const[c,v]of r){if(c===10){q={x:Number(v)*f,y:0};ps.push(q);}else if(c===20&&q)q.y=Number(v)*f;}if(ps.length<2)return raw(r,'invalid-leader');return make('cadLeader',{points:ps,text:'',height:num(r,40,2.5)*f});}
    return raw(r,'unsupported-entity');
   }catch(e){return raw(r,'invalid-or-unrepresentable-'+type+':'+e.message);}
  }
  let block=null;for(const r of records(ss.find(s=>s.name==='BLOCKS')?.pairs||[])){const type=first(r,0);if(type==='BLOCK'){block={name:first(r,2,''),base:point(r,10,f),rawHeader:clone(r),rawRecords:[]};rawBlocks.push(block);}else if(type==='ENDBLK'){if(block)block.rawEnd=clone(r);block=null;}else if(block)block.rawRecords.push(r);}
  for(const b of rawBlocks){if(/^\*MODEL_SPACE$|^\*PAPER_SPACE/i.test(b.name))continue;try{const members=b.rawRecords.map(entity),def={name:b.name,base:{x:0,y:0},dxfBase:b.base,dxfHeader:b.rawHeader,dxfEnd:b.rawEnd,readonly:b.name.includes('|')||Boolean(num(b.rawHeader,70)&(4|8|16|32)),objects:members.map(o=>root.cadBlocks.transformLeaf(o,root.cadBlocks.matrix({x:-b.base.x,y:-b.base.y}),{approximate:true}))};blockDefinitions.push(def);}catch(e){b.invalid=String(e.message);warn('BLOCK',b.name+':'+e.message);}}
  // Remove invalid dependency graphs independently; keep their source records for export.
  const dependencyMap=new Map(blockDefinitions.map(d=>[d.name.toUpperCase(),d])),invalid=new Set(),costs=new Map(),heights=new Map();
  function visit(name,path=new Set(),depth=0){const k=name.toUpperCase(),d=dependencyMap.get(k);if(!d||path.has(k)||depth>32||invalid.has(k))throw Error('invalid-block-graph');if(costs.has(k)){if(depth+heights.get(k)>32)throw Error('deep-block-graph');return costs.get(k);}const next=new Set(path);next.add(k);let total=0,h=0;for(const o of d.objects){total+=o.type==='cadInsert'?(root.cadBlocks.matrixValid(o.matrix)?visit(o.blockName,next,depth+1):(()=>{throw Error('invalid-block-matrix');})()):root.cadBlocks.memberCost(o);if(o.type==='cadInsert')h=Math.max(h,1+heights.get(o.blockName.toUpperCase()));if(total>100000)throw Error('block-expansion-budget');}heights.set(k,h);costs.set(k,total);return total;}
  for(const d of blockDefinitions)try{visit(d.name);}catch(e){invalid.add(d.name.toUpperCase());warn('BLOCK',d.name+':'+e.message);}
  for(let i=blockDefinitions.length-1;i>=0;i--)if(invalid.has(blockDefinitions[i].name.toUpperCase()))blockDefinitions.splice(i,1);

  const objects=model.map(r=>{counts[first(r,0)]=(counts[first(r,0)]||0)+1;const o=entity(r);if(o.type==='cadInsert'&&!blockDefinitions.some(d=>d.name.toUpperCase()===o.blockName.toUpperCase()))return raw(r,'unavailable-block-definition');return o;}),validNames=new Set(blockDefinitions.map(d=>d.name.toUpperCase())),preservedBlocks=rawBlocks.filter(b=>!validNames.has(b.name.toUpperCase())&&!/^\*MODEL_SPACE$|^\*PAPER_SPACE/i.test(b.name));
  for(const o of [...objects,...blockDefinitions.flatMap(d=>d.objects)])if(o.type==='cadDimension'&&!dimensionStyles.some(d=>d.name.toUpperCase()===o.styleName.toUpperCase())){const style=root.cadDimensionStyles?root.cadDimensionStyles.defaults(o.styleName):{name:o.styleName,textHeight:2.5,arrowSize:2.5,overallScale:100,precision:0,units:'mm',lengthFactor:1,arrow:'closed'};dimensionStyles.push(style);warnings.add('Missing DIMSTYLE preserved through a fallback: '+o.styleName);}
  root.cadBlocks.validate(blockDefinitions,objects);const archive={version:getHeader('$ACADVER','AC1009'),unitCode,unitFactor:f,sections:ss.filter(s=>!['BLOCKS','ENTITIES'].includes(s.name)),preservedBlocks,sourceObjectCount:model.length,diagnostics:clone(diagnostics),warnings:[...warnings]};return{objects,blockDefinitions,dimensionStyles,layerDefinitions,archive,diagnostics,warnings:[...warnings],counts,nextId:seq+1,unitFactor:f};
 }
 root.architecturalDxf=Object.freeze({capability:'cad.dxf.roundtrip.v1',decode,parse,pairs,sections,records,first,num,point,signature,aci,properties});
})();
